import Foundation

// MARK: - Supporting types

/// The lifecycle phase of the Game Night table, carried in every `tableState`.
enum GameNightPhase: String, Codable, Sendable {
    case settingTable
    case inProgress
    case completed
    case abandoned
}

/// One claimed seat as broadcast in `tableState`. `seatClaimID` is generated by
/// the claimer and remains stable; it maps to a `participantID` in the `Match`
/// once `matchStart` locks the table.
struct SeatSnapshot: Codable, Sendable {
    var seatClaimID: UUID
    var seat: Int
    var playerID: UUID?
    var displayName: String
    var displayInitials: String
    var displayThemeID: String
    /// True when this seat is owned by the same device that sent the `seatClaim`.
    var isLocal: Bool
}

/// Maps a `seatClaimID` (pre-lock identity) to the `participantID` assigned
/// inside the `Match` when `matchStart` fires.
struct SeatMapping: Codable, Sendable {
    var seatClaimID: UUID
    var participantID: UUID
}

// MARK: - Payload structs

/// Sent by every joiner on session join. The host checks `protocolVersion`
/// here and only here; a mismatch declines the seat.
struct HelloPayload: Codable, Sendable {
    let protocolVersion: Int
    let appVersion: String
}

/// Full seating snapshot broadcast by the host. Idempotent; also serves as the
/// late-join catch-up message. Carries the session-scoped commentary override
/// so every device knows who is in the booth tonight.
struct TableStatePayload: Codable, Sendable {
    let phase: GameNightPhase
    let seats: [SeatSnapshot]
    let commentaryEnabled: Bool
    let commentaryPackID: String
    let commentaryLevelRaw: String
}

/// Sent by a guest (or the host adding a local seat) to claim one seat.
struct SeatClaimPayload: Codable, Sendable {
    let seatClaimID: UUID
    let playerID: UUID?
    let displayName: String
    let displayInitials: String
    let displayThemeID: String
    /// True when this is an additional local seat on the claiming device.
    let isLocal: Bool
}

/// Locks the table. Carries the initial `Match` (no scores yet) plus the
/// mapping from pre-lock `seatClaimID`s to the `participantID`s inside it.
/// Each device uses this mapping to discover its own `participantID`.
/// On a resume, `match` carries the mid-game snapshot and `currentSeatIndex`
/// points to the interrupted turn's player.
struct MatchStartPayload: Codable, Sendable {
    let match: Match
    let seatMappings: [SeatMapping]
    let currentSeatIndex: Int
}

/// Sent by the roller at the moment dice are launched. Spectators replay the
/// recipe through their own physics engine.
struct RollBeganPayload: Codable, Sendable {
    let participantID: UUID
    /// Roll within the turn: 1, 2, or 3.
    let rollIndex: Int
    let recipe: DiceRollRecipe
    /// Held mask at roll time — self-contained so spectators don't race `holdToggled`.
    let heldMask: [Bool]
}

/// Sent by the roller when all dice have settled. Spectators compare each die's
/// replay face against these authoritative values and apply a silent correction
/// wobble for any mismatch.
struct RollResultPayload: Codable, Sendable {
    let participantID: UUID
    /// Five values, ordered by die index (0–4). Each value is 1–6.
    let faceValues: [Int]
}

/// Sent by the roller whenever a die's held state changes. Mirrors the
/// kinematic held line to spectator trays in real time.
struct HoldToggledPayload: Codable, Sendable {
    let participantID: UUID
    let dieIndex: Int
    let isHeld: Bool
}

/// Sent by the active scorer to propose a category. The host validates via
/// Layer 1 and applies. `diceValues` carries the roller's settled face values
/// so the host can run the same pure scoring functions without a separate dice-
/// state stream. In Phase 5 this will be superseded by `rollResult`.
struct ScoreChosenPayload: Codable, Sendable {
    let participantID: UUID
    let category: YatzyCategory
    /// Roller's settled face values at scoring time (5 values, 1–6).
    let diceValues: [Int]
}

/// Sent by the scorer to undo the most recent score entry, before the next
/// `rollBegan`. Host applies the existing `LastScoreSnapshot` undo path and
/// broadcasts `matchState`.
struct UndoRequestPayload: Codable, Sendable {
    let participantID: UUID
}

/// Full match snapshot broadcast after every applied action (score, undo, turn
/// advance). Normally transient dice state is omitted; spectators derive roll
/// count from the `rollBegan` stream. Exception: undo broadcasts include
/// `diceValues`/`rollsRemaining` so the undone player can rescore immediately.
struct MatchStatePayload: Codable, Sendable {
    let match: Match
    /// Index into `match.participants` for the seat whose turn it is.
    let currentSeatIndex: Int
    /// Pre-scoring dice values, present only in undo broadcasts.
    var diceValues: [Int]? = nil
    /// Rolls remaining for the seat, present only in undo broadcasts (always 0).
    var rollsRemaining: Int? = nil
}

/// Broadcast when the match completes. Every guest device upserts this `Match`
/// by UUID into its own local store — the single guest write of the session.
struct MatchCompletePayload: Codable, Sendable {
    let match: Match
}

/// Broadcast when the host abandons the session. Devices close gracefully.
/// Intentionally empty — the message kind is sufficient.
struct MatchAbandonedPayload: Codable, Sendable {}

/// Sent by a guest who voluntarily leaves during table setup, so the host
/// can remove their seat and rebroadcast the updated table state.
struct SeatReleasePayload: Codable, Sendable {
    let seatClaimID: UUID
}
