import Foundation
import SyLibCommentary

extension CommentaryPersonality where Kind == CommentaryEventKind {
    static let sports = CommentaryPersonality(
        id: "sports",
        displayName: "Sports",
        blurb: "The broadcast booth — energetic, hyperbolic, sports clichés for dice.",
        prosody: CommentaryProsody(rate: 0.54, pitchMultiplier: 1.08, preUtteranceDelay: 0.05, postUtteranceDelay: 0.05),
        previewLine: "Five of a kind, folks! The crowd is absolutely losing it right now!",
        lines: [
            "yatzyRolled": [
                "Yatzy! {player} brings the house down!",
                "Five of a kind! {player} rolls the perfect one, folks!",
                "Are you kidding me? {player} nails the Yatzy!",
                "That is a Yatzy for {player}, and the crowd goes wild!",
                "Textbook! Five dice, one face, all {player}!",
                "{player} calls their shot and delivers a Yatzy!",
                "Oh, {player} dialed that one up! Yatzy on the board!",
                "Five for five! {player} with the roll of the night!",
                "Send it! {player} lands the Yatzy clean!",
                "History right there, folks. {player} rolls a Yatzy!",
                "{player} steps up and drops fifty on us. Yatzy!",
                "Unbelievable scenes! Yatzy for {player}!",
                "That is what a Yatzy looks like, courtesy of {player}!",
                "Boom! {player} clears the whole board with five of a kind!",
                "{player} with the dagger. Yatzy, ballgame energy!",
                "Five matching dice for {player} and this table is electric!",
                "{player} came to play. That is a Yatzy!",
                "Perfect roll, perfect timing, all {player}. Yatzy!",
                "Right on the money! {player} rolls the fifty-pointer!",
                "And there it is! {player} joins the Yatzy club!",
                "{player} just made this look easy. Yatzy!"
            ],
            "yatzyBonusEarned": [
                "Another one?! {player} with the bonus Yatzy, plus a hundred!",
                "{player} is on fire! Back-to-back five of a kind!",
                "Stop it! {player} rolls ANOTHER Yatzy! Hundred more!",
                "The bonus is live and {player} is cashing it! A hundred points!",
                "{player} does it again, folks! Bonus Yatzy!",
                "Lightning strikes twice for {player}! Plus one hundred!",
                "Who does that? {player} does that! Another Yatzy!",
                "{player} just added a hundred like it was nothing!",
                "Encore! {player} rolls the bonus five of a kind!",
                "That's a second Yatzy for {player} and the booth is losing it!",
                "{player} keeps rolling and the points keep coming! Hundred more!",
                "Absolute heater from {player}! Bonus Yatzy on the board!",
                "{player} is in the zone! Another hundred, another Yatzy!",
                "Ridiculous! {player} stacks a bonus Yatzy!",
                "The hot hand stays hot! {player}, plus one hundred!",
                "{player} with the repeat performance! Bonus points!",
                "Again?! {player} cannot be stopped! Another Yatzy!",
                "Cash it in, {player}! A hundred-point bonus Yatzy!",
                "{player} rolls a second five of a kind! Unreal!",
                "The bonus banner is up! {player} adds one hundred!",
                "{player} just turned this into a highlight reel!"
            ],
            "winnerDeclared": [
                "That's the ballgame! {winner} takes it with {score}!",
                "Final score, {winner} on top! What a performance!",
                "{winner} wins it, folks! {score} points and a trophy!",
                "Ballgame! {winner} holds off {runnerUp} for the title!",
                "{winner} closes it out! Champion, right here!",
                "It's over, and {winner} stands alone! {score} to win!",
                "{winner} brings it home by {margin}! Sensational!",
                "Your winner tonight, {winner}, with {score}!",
                "{winner} seals the deal! {runnerUp} left in second!",
                "Final horn! {winner} is your champion!",
                "{winner} finishes strong and takes the crown!",
                "What a run by {winner}! Winner, {score} points!",
                "{winner} did it! Edging {runnerUp} for the win!",
                "Game, set, match, {winner}! {score} on the board!",
                "{winner} climbs to the top! Champion by {margin}!",
                "And {winner} takes it! The comeback complete!",
                "{winner} wins the night! Textbook finish!",
                "Final tally, {winner} on top with {score}!",
                "{winner} outlasts the field! Your winner!",
                "Champagne for {winner}! The title is theirs!",
                "{winner} closes the show! {score} and the win!"
            ],
            "winnerTie": [
                "We've got a tie! {winner}, deadlocked at {score}!",
                "Photo finish, folks! {winner} share the top!",
                "No separation! {winner} tied at {score}!",
                "Dead heat! {winner} both on top!",
                "Unbelievable, a tie! {winner} split the crown!",
                "Nobody blinks! {winner} finish level at {score}!",
                "It's all square! {winner} tied for the win!",
                "What a finish! {winner} can't be separated!",
                "Even Steven! {winner} share it at {score}!",
                "A tie for the ages! {winner} both champions!",
                "Deadlocked! {winner} tied to the point!",
                "They match to the number! {winner}, {score} apiece!",
                "No winner alone tonight! {winner} share it!",
                "A draw! {winner} both walk away on top!"
            ],
            "upperBonusEarned": [
                "{player} locks in the upper bonus! Thirty-five more!",
                "There's the bonus! {player} cracks sixty-three!",
                "{player} does the upper work and cashes in! Plus thirty-five!",
                "Bonus secured! {player} banks the thirty-five!",
                "{player} grinds it out and gets the upper bonus!",
                "Smart play by {player}! The bonus is theirs!",
                "{player} hits the number! Thirty-five-point bonus!",
                "Upper section, handled! {player} takes the bonus!",
                "{player} punches the ticket! Bonus points on the board!",
                "That's the bonus for {player}! The fundamentals pay off!",
                "{player} clears sixty-three and pockets thirty-five!",
                "Bonus in the bank for {player}!",
                "{player} plays it right and gets rewarded! Upper bonus!",
                "There it is, the thirty-five! Nice work, {player}!",
                "{player} secures the upper bonus like a pro!",
                "Ballgame fundamentals from {player}! Bonus earned!",
                "{player} tops the threshold! Thirty-five, please!",
                "The upper bonus belongs to {player}!",
                "{player} closes the upper section in style! Bonus!",
                "Thirty-five points, courtesy of {player}'s discipline!"
            ],
            "yatzyScratched": [
                "Ohh, {player} scratches the Yatzy! No bonus insurance now!",
                "Big swing! {player} zeroes out the Yatzy box!",
                "That's a scratch on the Yatzy for {player}! Gutsy or grim, you decide!",
                "{player} takes a zero on the Yatzy! The bonus door slams shut!",
                "Yikes! {player} lets the Yatzy go for nothing!",
                "{player} scratches the fifty-pointer! No safety net!",
                "There goes the Yatzy box, zeroed by {player}!",
                "{player} eats a zero up top! No more bonus chances!",
                "Tough break, folks! {player} scratches the Yatzy!",
                "{player} writes a zero where fifty could've been!",
                "The Yatzy box is dead for {player}! Scratched!",
                "{player} sacrifices the Yatzy! High-stakes stuff!",
                "Zero on the Yatzy! {player} closes that door!",
                "{player} scratches it! No bonus Yatzy in this player's future!",
                "Painful! {player} takes nothing on the Yatzy!",
                "{player} zeroes the big box! The gamble is on!",
                "That's a scratch, {player}! The Yatzy's off the table!",
                "{player} lets the fifty slip to zero!",
                "No Yatzy for {player} tonight! Scratched clean!",
                "{player} poisons the box! Zero on the Yatzy!"
            ],
            "bigTurn": [
                "{player} drops a {category} for {value}! Big points!",
                "That's a {category}! {player} banks {value}!",
                "{player} with the {category}, worth {value}!",
                "Huge turn! {player} scores {value} on the {category}!",
                "{player} cashes the {category}! {value} on the board!",
                "Order up! {player} completes the {category} for {value}!",
                "{player} nails the {category}! That's {value}, folks!",
                "Big number from {player}! {category}, {value} points!",
                "{player} lines up the {category}! {value}!",
                "There's the {category} for {player}! {value} points!",
                "{player} delivers the {category}! {value} banked!",
                "Textbook {category} by {player}! {value}!",
                "{player} strikes gold! {category} for {value}!",
                "{player} loads up the {category}! {value} points!",
                "Momentum swing! {player} scores {value} on the {category}!",
                "{player} with a statement {category}! {value}!",
                "That'll move the needle! {player}, {category}, {value}!",
                "{player} takes the {category} and runs! {value}!",
                "Big-time roll! {player} banks {value} with the {category}!",
                "{player} finishes the {category} in style! {value}!"
            ],
            "leadChange": [
                "New leader! {leader} surges past {runnerUp}!",
                "And {leader} takes the lead! What a swing!",
                "{leader} moves to the front! {runnerUp} bumped to second!",
                "Lead change! {leader} is your new front-runner!",
                "{leader} storms into first! {runnerUp} gives chase!",
                "There's the swing! {leader} on top now!",
                "{leader} grabs the lead from {runnerUp}!",
                "The order flips! {leader} leads!",
                "{leader} vaults ahead! {runnerUp} in the rearview!",
                "New number one! {leader} takes command!",
                "{leader} snatches the lead! Game on!",
                "{runnerUp} yields the top spot to {leader}!",
                "{leader} is out front! The race is heating up!",
                "And just like that, {leader} leads!",
                "{leader} overtakes {runnerUp}! Momentum shift!",
                "The lead is {leader}'s now! Big move!",
                "{leader} pulls to the front! Watch out, {runnerUp}!",
                "Changing of the guard! {leader} on top!",
                "{leader} takes over first place!",
                "{runnerUp} led, but now it's all {leader}!"
            ],
            "turnStart": [
                "{player} steps up to the tray!",
                "Here comes {player}!",
                "{player} is on the clock!",
                "Up next, {player}!",
                "{player} takes the dice!",
                "It's {player}'s turn, folks!",
                "{player} ready to roll!",
                "All eyes on {player}!",
                "{player} at the table!",
                "Here's {player}!",
                "{player} to the dice!",
                "{player}'s up!",
                "Let's see what {player} has!",
                "{player} takes their shot!",
                "The dice are {player}'s!",
                "{player} on deck and rolling!",
                "Over to {player}!",
                "{player} enters the arena!",
                "{player} steps in!",
                "Time for {player}!"
            ],
            "categoryScored": [
                "{player} takes {value} on the {category}.",
                "{category} for {player}, {value} points.",
                "{player} banks {value} on the {category}!",
                "On the board! {player} with {value} on the {category}!",
                "{player} scores the {category}. {value}.",
                "That's {value} for {player} on the {category}!",
                "{player} plays the {category}. {value}.",
                "{value} points on the {category} for {player}!",
                "{player} logs {value} on the {category}.",
                "Solid {category}, {value} for {player}!",
                "{player} adds {value} with the {category}!",
                "{category}, {value}. {player} keeps moving.",
                "{player} puts up {value} on the {category}!",
                "{value} in the books, {category} for {player}!",
                "{player} takes care of the {category}. {value}.",
                "{category} points for {player}, {value}!",
                "{player} chalks up {value} on the {category}!",
                "That's the {category}, {value}, {player}.",
                "{player} moves the total with a {category}. {value}!",
                "{value} more on the {category} for {player}!"
            ],
            "categoryScratched": [
                "{player} scratches the {category}. Zero there.",
                "Nothing on the {category} for {player}.",
                "{player} takes a zero on the {category}.",
                "That's a scratch, {player}. {category}, zero.",
                "{player} lets the {category} go.",
                "Zero on the {category} for {player}.",
                "{player} eats a goose egg on the {category}.",
                "No points on the {category}, {player}.",
                "{player} writes off the {category}.",
                "A scratch on the {category} for {player}.",
                "{player} zeroes the {category}.",
                "{category}, zero. Tough one, {player}.",
                "{player} sacrifices the {category}.",
                "Nothing doing on the {category} for {player}.",
                "{player} clears the {category} at zero.",
                "Zero there, {player}. On to the next.",
                "{player} bites the bullet on the {category}.",
                "Scratch on the {category}, {player}.",
                "{player} takes nothing on the {category}.",
                "{category} goes empty for {player}."
            ]
        ]
    )
}
