import Foundation
import SyLibCommentary

extension CommentaryPersonality where Kind == CommentaryEventKind {
    static let snarky = CommentaryPersonality(
        id: "snarky",
        displayName: "Snarky",
        blurb: "The deadpan wit — dry, playful, mock-dramatic. Ribs the roll, never the person.",
        prosody: CommentaryProsody(rate: 0.48, pitchMultiplier: 0.98, preUtteranceDelay: 0.20, postUtteranceDelay: 0.15),
        previewLine: "Five of a kind. The dice clearly have a favorite tonight. Suspicious.",
        lines: [
            "yatzyRolled": [
                "A Yatzy. {player} is going to be insufferable now.",
                "Five of a kind. The dice clearly like {player} better than the rest of us.",
                "Oh good, a Yatzy. {player} will remind everyone of this for weeks.",
                "{player} rolls a Yatzy. Statistically rude.",
                "Five matching dice. {player} did that on purpose, apparently.",
                "A Yatzy for {player}. The rest of the table would like to lodge a complaint.",
                "Well. {player} just peaked. Downhill from here.",
                "Five of a kind. {player}, save some luck for the others.",
                "A Yatzy. Somewhere a probability textbook is crying.",
                "{player} lands the Yatzy and acts like it was skill.",
                "Fifty points, and {player} definitely called it. Sure.",
                "Five dice, one face. {player} is officially unbearable.",
                "A Yatzy. {player} would like everyone to remember this moment forever.",
                "The dice rolled over for {player}. Traitors.",
                "{player} gets a Yatzy. The others are handling it beautifully. Not.",
                "Five of a kind. {player} earned it, or bribed the dice. Unclear.",
                "Congratulations to {player}, and condolences to everyone else.",
                "A Yatzy. Cool, cool, totally fine, no notes.",
                "{player} rolls five of a kind and the group chat will never recover.",
                "Well rolled, {player}. Nobody's jealous. Everyone's jealous.",
                "A Yatzy for {player}. The dice have chosen a favorite and it isn't you, reader.",
                "A Yatzy for {player}. The dice have been compromised.",
                "Five of a kind. {player} will be describing this at length.",
                "{player} rolls a Yatzy. Nobody panic, just quietly resent it.",
                "Oh look, {player} got the good one. How novel.",
                "A Yatzy. {player} is now legally allowed to be smug.",
                "{player} rolls five of a kind and immediately becomes a different person.",
                "Five matching dice. {player} has peaked, and everyone saw it.",
                "A Yatzy for {player}. The table applauds through gritted teeth.",
                "{player} lands the fifty. Skill, obviously. Definitely skill.",
                "Five of a kind. The physics has picked a side, and it is {player}.",
                "A Yatzy. {player}, please pretend to be surprised.",
                "{player} rolls the Yatzy and the mood in the room changes.",
                "Fifty points to {player}. That is going on the fridge.",
                "Five identical faces. {player} did nothing to deserve this. Neither did we.",
                "A Yatzy for {player}. Statistically unlikely, socially devastating.",
                "{player} gets the big one. The dice have favorites and they are shameless.",
                "Well, {player} rolled a Yatzy. Enjoy the commentary that follows.",
                "Five of a kind for {player}. Everyone else, keep breathing.",
                "A Yatzy. {player} will absolutely bring this up at dinner.",
                "{player} takes the fifty. Some people are just handed things.",
                "Five dice, one face, zero humility incoming. Nice roll, {player}."
            ],
            "yatzyBonusEarned": [
                "Another Yatzy. {player} is just showing off now.",
                "A second five of a kind. {player}, leave some for the class.",
                "Oh, a bonus Yatzy. {player} definitely needed the extra hundred.",
                "{player} rolls another one. The dice have a clear agenda.",
                "Two Yatzys. {player} is writing a book about it as we speak.",
                "Bonus hundred for {player}. The others are thrilled. Visibly.",
                "Again? {player}, this is getting embarrassing for everyone else.",
                "A repeat Yatzy. {player} has clearly made a deal with someone.",
                "{player} adds a hundred. Somewhere, math is offended.",
                "Another five of a kind. {player} is not even trying to be humble.",
                "Two in a game. {player} will mention this at the funeral.",
                "Bonus Yatzy. {player}, the dice are practically autographing themselves.",
                "{player} does it again. The table's morale is doing great. Not.",
                "A second hundred. {player} is basically cheating with permission.",
                "Encore Yatzy for {player}. Nobody asked, but here we are.",
                "{player} rolls another. The other players have questions.",
                "Two Yatzys. {player} is one away from being challenged to a duel.",
                "Bonus points for {player}. Skill, luck, or witchcraft. Pick one.",
                "Another one. {player} is speedrunning smugness.",
                "{player} stacks a hundred. The dice know exactly what they're doing.",
                "A repeat Yatzy. Truly inspiring. Truly annoying. Both, {player}.",
                "Another one. {player} is now just bullying the table.",
                "A second Yatzy for {player}. The dice have signed a contract.",
                "Bonus hundred. {player} did not need it, which is the point.",
                "{player} rolls another five of a kind. This is getting out of hand.",
                "Two Yatzys. {player} is going to be unbearable at every future game.",
                "Another hundred to {player}. Nobody is having fun except {player}.",
                "{player} does it twice. The odds have filed a complaint.",
                "A bonus Yatzy. {player} is clearly cheating in a way we cannot prove.",
                "{player} adds a hundred. The others are recalculating their friendships.",
                "Second five of a kind. {player} has entered legend mode. Insufferably.",
                "Bonus points for {player}. Cool. Great. Wonderful. Fine.",
                "{player} rolls another Yatzy. The dice are showing off through a proxy.",
                "Two in one game. {player} will not stop talking about this. Ever.",
                "A hundred more for {player}. Anyone else feeling targeted?",
                "{player} repeats the miracle. The miracle is getting annoying.",
                "Another bonus Yatzy. {player} is playing a different game entirely.",
                "{player} banks a hundred. The rest of you can have the moral victory.",
                "A second Yatzy. Somewhere the concept of fairness is lying down.",
                "{player} does it again, casually, which makes it worse.",
                "Bonus five of a kind. {player} is out of control and loving it.",
                "Another hundred for {player}. Statistically fine. Emotionally not."
            ],
            "winnerDeclared": [
                "{winner} wins. Everyone act surprised.",
                "And the winner is {winner}, who will absolutely bring this up again.",
                "{winner} takes it by {margin}. {runnerUp} is fine. {runnerUp} is totally fine.",
                "Congratulations, {winner}. The dice apologize to everyone else.",
                "{winner} wins with {score}. A number they will have tattooed by morning.",
                "It's over. {winner} won, and now we all have to hear about it.",
                "{winner} on top. {runnerUp}, so close, which is somehow worse.",
                "Winner, {winner}. Please contain your gloating. You won't.",
                "{winner} takes it. The rematch demands are already forming.",
                "{winner} wins by {margin}. Rounding up, that's a lot.",
                "And {winner} closes it out. Humble in victory. Kidding. Not humble.",
                "{winner} first. The dice have spoken and they were extremely biased.",
                "{score} for the win. {winner} peaked at the perfect time. Annoying.",
                "{winner} wins. {runnerUp} led for a while, which they'll mention forever.",
                "Victory for {winner}. Everyone clap, some of you mean it.",
                "{winner} takes the crown. It's a paper one, but still.",
                "Game over. {winner} won. Physics remains undefeated.",
                "{winner} on top by {margin}. Screenshot it, they will.",
                "And that's a win for {winner}. The trash talk starts in three, two, one.",
                "{winner} wins. {runnerUp} played great and lost anyway. Delightful.",
                "Your champion, {winner}, who definitely won't rig the next one. Probably.",
                "{winner} wins with {score}. The rematch is already scheduled.",
                "That is a win for {winner}. {runnerUp} would like it noted they tried.",
                "{winner} takes it by {margin}. A margin that will grow in the retelling.",
                "Game over. {winner} won and the dice will not be taking questions.",
                "{winner} first. {runnerUp} second, which is just first from the back.",
                "The winner is {winner}. Try to look happy for them.",
                "{winner} wins. Somewhere, a scorecard weeps for {runnerUp}.",
                "{score} points and a win for {winner}. Modesty sold separately.",
                "{winner} closes it out. The victory lap starts immediately.",
                "And it is {winner} by {margin}. Barely counts. Counts completely.",
                "{winner} takes the game. Everyone else takes it personally.",
                "Winner, {winner}. Second, {runnerUp}. Third, everyone's dignity.",
                "{winner} wins with {score}. That number will be quoted wrong forever.",
                "It is over. {winner} on top, as they will remind us.",
                "{winner} finishes first. {runnerUp}, the moral victory is all yours.",
                "{winner} wins. Please hold your applause until they demand it.",
                "That is the game, and {winner} is unbearably pleased.",
                "{winner} by {margin}. A gap they will describe as a chasm.",
                "{winner} takes the win. The rematch begins the moment someone dares.",
                "Final score {score}. {winner} wins, and nobody is remotely surprised.",
                "{winner} is the champion. The dice, as ever, decline to explain themselves."
            ],
            "winnerTie": [
                "A tie. Nobody wins, everybody argues.",
                "{winner} tied at {score}. A rematch is now legally required.",
                "It's a draw. {winner} will each claim they really won.",
                "{winner} finish level. The universe declines to pick a favorite.",
                "A tie. {winner}, please resolve this outside.",
                "Deadlocked at {score}. {winner} both insufferable, equally.",
                "{winner} tied. The dice took the coward's way out.",
                "A draw. {winner} share the trophy, which is one trophy. Good luck.",
                "{winner} match exactly. Somebody count again, surely.",
                "It's even. {winner} both win, which means nobody gets to gloat properly.",
                "A tie. {winner}, this is the worst possible outcome for peace.",
                "{winner} at {score} apiece. Sudden death is the only civilized option.",
                "Level game. {winner} will litigate this for years.",
                "A tie. Congratulations to {winner}, and to chaos.",
                "A tie. The dice took the easy way out again.",
                "{winner} both on {score}. Excellent, now nobody can be gracious.",
                "It is level. {winner} will both claim moral superiority.",
                "A draw for {winner}. Perfect. Truly the worst ending.",
                "{winner} tied. Somebody is going to demand a tiebreaker. Loudly.",
                "Even at {score}. {winner}, this settles nothing.",
                "A tie. {winner} share the victory and none of the satisfaction.",
                "{winner} finish identical. The universe is having a laugh.",
                "Deadlocked. {winner} both winners, both furious.",
                "A draw. {winner}, please shake hands and pretend.",
                "{winner} at {score} each. The rematch is not optional.",
                "It is a tie. Congratulations to nobody in particular.",
                "{winner} match exactly. Recount demanded in three, two...",
                "A tie for {winner}. The most unsatisfying number is equal."
            ],
            "upperBonusEarned": [
                "{player} got the upper bonus. Someone read the rules.",
                "Thirty-five bonus points for {player}. The nerds call this strategy.",
                "{player} cleared sixty-three. Suspiciously competent.",
                "Upper bonus for {player}. Playing to win, are we.",
                "{player} banks the thirty-five. Look who did their homework.",
                "The bonus goes to {player}, who apparently planned ahead. Show-off.",
                "{player} hit sixty-three. That's a lot of ones and twos of patience.",
                "Bonus secured. {player} is taking this seriously now.",
                "{player} gets thirty-five for good behavior. Rare.",
                "Upper bonus, {player}. The tortoise strategy pays off.",
                "{player} managed the boring section and got paid. Fine, well done.",
                "Thirty-five points for {player}'s spreadsheet energy.",
                "{player} cleared the threshold. Somebody's competitive.",
                "The bonus lands with {player}, who definitely counted first.",
                "{player} earns thirty-five. The upper section's revenge.",
                "Upper bonus for {player}. Discipline. Gross.",
                "{player} hit sixty-three exactly, probably on purpose. Menace.",
                "Thirty-five bonus. {player} is playing chess, we're playing checkers.",
                "{player} got the bonus and a smug little nod, no doubt.",
                "Bonus points, {player}. The math homework paid off after all.",
                "{player} got the upper bonus. Someone has been paying attention. Rude.",
                "Thirty-five for {player}. The slow, boring path pays. Annoying.",
                "{player} cleared sixty-three. Discipline strikes again.",
                "Upper bonus. {player} apparently reads the scorecard. Overachiever.",
                "{player} banks thirty-five for being sensible. Gross.",
                "The bonus goes to {player}, who did the unglamorous work. Fine. Fine.",
                "{player} hit the threshold. Somebody has a plan and it is working.",
                "Thirty-five points for {player}'s patience. Patience is basically cheating.",
                "{player} earns the upper bonus. Look at this responsible adult.",
                "Bonus secured by {player}. The rest of you were chasing straights.",
                "{player} gets thirty-five. Boring, effective, infuriating.",
                "Upper bonus for {player}. The tortoise wins again. Ugh.",
                "{player} counted correctly. Show-off.",
                "Thirty-five to {player}. Strategy: apparently a thing.",
                "{player} clears sixty-three with room to spare. Smug incoming.",
                "The bonus lands with {player}. Somebody read the fine print.",
                "{player} takes the thirty-five. Method over mayhem. Disappointing.",
                "Upper bonus, {player}. The sixes did the heavy lifting, but sure.",
                "{player} gets paid for good habits. A terrible precedent.",
                "Thirty-five bonus points. {player} planned this. Suspicious."
            ],
            "yatzyScratched": [
                "{player} scratched the Yatzy. Bold. Reckless. Both.",
                "A zero on the Yatzy. {player} lives dangerously.",
                "{player} just poisoned the box. No takebacks, no bonus, no mercy.",
                "And {player} scratches the Yatzy. Future self will love that.",
                "Zero on the fifty-pointer. {player} plays fast and loose.",
                "{player} sacrifices the Yatzy. The dice noted your address.",
                "A scratch. {player} said no thank you to a hundred future points.",
                "{player} zeroes the Yatzy box. Chaos reigns.",
                "{player} scratched it. Somewhere a strategy guide fainted.",
                "Zero on the Yatzy. {player} is either a genius or not. Not.",
                "{player} closes the bonus door and throws away the key.",
                "A poisoned box, courtesy of {player}. Live footage of a decision.",
                "{player} scratches the Yatzy. The other players say nothing. They're thrilled.",
                "Zero. {player} gambled the fifty and the house always remembers.",
                "{player} just gave up the Yatzy. Confidence or panic. We'll never know.",
                "The Yatzy box, zeroed by {player}. Fortune favors the... not this.",
                "{player} scratched it. Somewhere, a math teacher wept.",
                "A zero on the Yatzy. {player} enjoys living without a safety net.",
                "{player} poisons the box. The dice will absolutely hold a grudge.",
                "Scratched. {player}, that's going to be a fun one to explain later.",
                "{player} zeroes the Yatzy. Confidence is a beautiful thing to watch fail.",
                "Scratched. {player} has decided fifty points are for other people.",
                "{player} kills the Yatzy box. This just got interesting. For us.",
                "Zero on the Yatzy. {player} is playing four-dimensional chess. Allegedly.",
                "{player} throws away the fifty. The dice are taking notes.",
                "A scratch on the big one. {player} regrets nothing. Yet.",
                "{player} poisons the Yatzy. That decision has a long tail.",
                "Zero. {player} said no to a hundred future points. Very brave.",
                "{player} scratches the Yatzy. Somewhere a strategy guide is being rewritten.",
                "The Yatzy box, dead. {player} did that on purpose. Reportedly.",
                "{player} takes a zero on the fifty. Bold. Deeply questionable. Bold.",
                "Scratched, and the bonus door is welded shut. Nice work, {player}.",
                "{player} lets the Yatzy go. Future {player} will have opinions.",
                "Zero on the Yatzy. {player} enjoys risk and, apparently, disappointment.",
                "{player} sacrifices the big box. The dice remember faces.",
                "A zero where fifty lived. {player} is committed to the chaos.",
                "{player} scratches. Every five of a kind from here is worth nothing extra.",
                "The Yatzy is gone, courtesy of {player}. Enjoy the consequences.",
                "{player} zeroes it out. Somewhere, probability shrugs.",
                "Scratched Yatzy for {player}. That will look great in the highlights. It will not."
            ],
            "bigTurn": [
                "{player} scores a {category} for {value}. Look at that, actual competence.",
                "A {category} worth {value}. {player} is trying now. Concerning.",
                "{player} banks {value} on the {category}. Suspiciously well played.",
                "{value} points on the {category}. {player} means business, apparently.",
                "{player} lands the {category}. {value}. Beginner's luck? Rude either way.",
                "A big {category} from {player}. The rest of you might want to wake up.",
                "{player} takes {value}. That {category} won't shut up about itself.",
                "{category} for {value}. {player} is making the rest look decorative.",
                "{player} scores {value}. The dice are cooperating a little too eagerly.",
                "A {category}, {value} points. {player} found the good roll. Hoarding, really.",
                "{player} banks the {category}. {value}. Someone's feeling themselves.",
                "{value} on the {category}. {player}, save some points for the others.",
                "{player} completes the {category}. {value}. Textbook. Insufferably so.",
                "A {category} worth {value}. {player} is climbing. Ugh, effective.",
                "{player} takes {value}. The {category} gods smiled. Favoritism, clearly.",
                "{value} points, {player}. That {category} is going straight to your head.",
                "{player} scores the {category}. {value}. Fine. That was good. Don't gloat.",
                "A tidy {category} for {value}. {player} is peaking suspiciously well.",
                "{player} banks {value}. The {category} came easy. Some people have all the luck.",
                "{value} on the {category}. {player} is quietly running away with this. Quietly.",
                "{player} scores {value} on the {category}. Alarming competence.",
                "A {category} for {value}. {player} is doing this on purpose now.",
                "{value} points to {player}. That {category} was practically gift-wrapped.",
                "{player} takes the {category}. {value}. Everyone else, take notes. Reluctantly.",
                "Big {category}. {player} banks {value} and pretends to be humble.",
                "{value} on the {category}. {player} is quietly running away with this.",
                "{player} lands the {category} for {value}. Fine. Good roll. Moving on.",
                "A {category} worth {value}. {player} did not need that much help.",
                "{player} scores {value}. The dice are being very generous. To {player}.",
                "{value} points. {player} makes the {category} look routine. Show-off.",
                "{player} takes the {category}. {value}. The scoreboard sighs.",
                "That is {value} for {player}. Somebody is peaking on schedule.",
                "{player} banks the {category} for {value}. Well played. Unfortunately.",
                "A tidy {value} on the {category}. {player} is not even sweating.",
                "{player} scores {value}. Everyone else is now doing math nervously.",
                "{category} for {value}. {player} is having a night. Some of us are not.",
                "{player} takes {value} and a little more of everyone's hope.",
                "{value} on the {category}. {player} makes it look boring. It is not.",
                "{player} converts the {category} for {value}. Efficient. Irritating.",
                "A big {category}, {value} points. {player} is officially a problem."
            ],
            "leadChange": [
                "{leader} takes the lead. {runnerUp} did not care for that.",
                "New leader, {leader}. The peace was nice while it lasted.",
                "{leader} passes {runnerUp}. Betrayal, honestly.",
                "And {leader} grabs the lead. {runnerUp} is fine. {runnerUp} is seething.",
                "{leader} in front now. {runnerUp} would like a word.",
                "Lead change. {leader} on top, and loving it too much.",
                "{leader} overtakes {runnerUp}. The alliance is over.",
                "{leader} takes first. {runnerUp}, that spot was warm.",
                "{leader} leads now. Screenshot it, it won't last.",
                "{runnerUp} loses the lead to {leader}. Awkward at the table.",
                "{leader} muscles ahead. {runnerUp} is drafting a strongly worded rebuttal.",
                "New number one, {leader}. {runnerUp} has entered their villain arc.",
                "{leader} takes the lead. Enjoy the view, it's a rental.",
                "{leader} ahead of {runnerUp} now. The tension is delicious.",
                "{leader} steals first. {runnerUp} remembers this.",
                "And {leader} leads. {runnerUp} would like to speak to the dice's manager.",
                "{leader} up front. {runnerUp} pretending not to mind. Failing.",
                "{leader} takes over. {runnerUp}, welcome to second.",
                "{leader} leads now, briefly, probably, we'll see.",
                "{leader} passes {runnerUp}. Somewhere a friendship strains.",
                "{leader} takes the lead. {runnerUp} is processing that publicly.",
                "New leader, {leader}. The mood at the table just curdled.",
                "{leader} passes {runnerUp}. No hard feelings. Many hard feelings.",
                "{leader} in front now. {runnerUp} is doing math and disliking it.",
                "The lead goes to {leader}. {runnerUp} would like a formal inquiry.",
                "{leader} on top. Enjoy it, these things are seasonal.",
                "{leader} moves ahead. {runnerUp} pretends this was the plan.",
                "Lead change. {leader} first, {runnerUp} newly motivated.",
                "{leader} claims the top spot. {runnerUp} claims the dice are broken.",
                "{leader} leads now. Somewhere an alliance quietly dissolves.",
                "{leader} overtakes {runnerUp}. The table temperature drops.",
                "New number one, {leader}. Second place is a mood, {runnerUp}.",
                "{leader} in the lead. This will absolutely be avenged.",
                "{leader} takes over. {runnerUp} is fine, in the way people say fine.",
                "{leader} ahead of {runnerUp} now. Awkward. Delicious.",
                "The lead flips to {leader}. Everyone recalculates their grudges.",
                "{leader} first. {runnerUp}, that was a nice run while it lasted.",
                "{leader} steps in front. The dice have chosen a side.",
                "{leader} leads. {runnerUp} has entered a thoughtful silence.",
                "{leader} takes the lead. The bill comes due at the end of the game."
            ],
            "turnStart": [
                "{player}'s turn. Try to make it count.",
                "Up next, {player}. No pressure. Some pressure.",
                "{player}, the dice await your questionable decisions.",
                "It's {player}'s turn. Let's see the strategy. Or lack of.",
                "{player} takes the dice. Good luck, you'll need it.",
                "Over to {player}. The bar is low, clear it.",
                "{player}, your moment to disappoint the dice.",
                "{player}'s up. Fingers crossed, everyone.",
                "Now {player}. Whenever the confidence arrives.",
                "{player} rolls next. This should be interesting. Or not.",
                "{player}, the tray is yours. Handle it.",
                "Turn's yours, {player}. Don't overthink it, you will.",
                "{player} steps up. Bold of you.",
                "Here's {player}, live and probably unprepared.",
                "{player}'s turn. The dice have low expectations.",
                "Go on then, {player}. Amaze us. Or don't.",
                "{player} takes over. History is watching, sort of.",
                "{player}, roll the dice and pray.",
                "Up you go, {player}. We believe in you. Mostly.",
                "It's {player}'s turn. Set your expectations accordingly.",
                "{player}'s turn. Expectations: managed.",
                "Here comes {player}. Brace accordingly.",
                "{player}, the dice are yours. Do try.",
                "It is {player}'s turn. Anything could happen. Mostly nothing.",
                "{player} rolls next. The suspense is moderate.",
                "Over to {player}. Let us see the master plan.",
                "{player} takes the tray. Confidence not included.",
                "Your go, {player}. No takebacks.",
                "{player} steps up. The dice are unimpressed already.",
                "Now {player}. Try to look like you meant it.",
                "{player}, off you go. Eventually, apparently.",
                "It is {player}'s moment. Blink and you will miss the strategy.",
                "{player} is up. Somebody wake the dice.",
                "Turn's yours, {player}. Make it worth the wait.",
                "{player} rolls. The rest of us wait, patiently, mostly.",
                "Here we go again. {player}'s turn.",
                "{player}, the table is watching. No pressure. Enormous pressure.",
                "Next up, {player}, who has a plan. Probably.",
                "{player} takes their shot. Aim optional.",
                "Go on, {player}. Astonish somebody."
            ],
            "categoryScored": [
                "{player} takes {value} on the {category}. Bold choice. We'll allow it.",
                "{value} for the {category}. {player} is playing it safe. Yawn.",
                "{player} scores {value} on the {category}. Riveting stuff.",
                "The {category} for {value}. {player} shrugs and moves on.",
                "{value} on the {category}. {player}. Groundbreaking.",
                "{player} fills the {category}. {value}. Adequate.",
                "That's {value} on the {category}, {player}. The crowd is stunned. Not.",
                "{player} banks {value} on the {category}. Living on the edge, clearly.",
                "A {category} for {value}. {player} keeps the dream barely alive.",
                "{value} on the {category}. {player}, you had to score somewhere.",
                "{player} takes the {category}. {value}. Sure, why not.",
                "{value} for {player} on the {category}. Every little bit helps. Barely.",
                "The {category}, {value}. {player} settles.",
                "{player} logs {value} on the {category}. The suspense is underwhelming.",
                "{value} on the {category}. {player} plays the percentages. Cowardly.",
                "{player} scores the {category} for {value}. History will not remember this.",
                "A {value} on the {category}. Points are points, {player}. Allegedly.",
                "{player} takes {value} on the {category} and calls it a day.",
                "{value} on the {category}. That'll... do something, {player}.",
                "The {category} for {value}. {player} soldiers on. Barely.",
                "{player} takes {value} on the {category}. Thrilling.",
                "{value} on the {category}. {player} is playing the long game. Or hiding.",
                "{player} scores the {category}. {value}. It counts, technically.",
                "A {category} for {value}. {player} is out here doing the minimum.",
                "{player} banks {value}. Nobody is writing songs about it.",
                "{value} points on the {category}. {player} takes what they can get.",
                "{player} fills the {category}. {value}. Efficient. Joyless. Effective.",
                "That is {value} for {player}. The scoreboard barely notices.",
                "{player} logs the {category} at {value}. Bureaucracy in action.",
                "{value} on the {category}. {player} calls that a plan.",
                "{player} scores {value}. The dice offered little. {player} accepted less.",
                "A {category}, {value}. {player} is surviving, not thriving.",
                "{player} takes {value}. Somewhere, ambition weeps quietly.",
                "{value} for the {category}. {player} keeps the lights on.",
                "{player} fills a box. {value}. Progress, allegedly.",
                "The {category} for {value}. {player} plays it safe. Again.",
                "{player} adds {value}. The comeback continues at a crawl.",
                "{value} on the {category}. Points are points, {player}. Small ones.",
                "{player} takes the {category}. {value}. Do not spend it all at once.",
                "A {value} on the {category}. {player} shrugs, the dice shrug back."
            ],
            "categoryScratched": [
                "{player} scratches the {category}. That'll haunt them.",
                "Zero on the {category}. {player} had bigger plans, clearly.",
                "{player} takes a zero. Strategic. Allegedly.",
                "A scratch on the {category}. {player} is gambling with the math.",
                "{player} zeroes the {category}. Bold. Or panicked. Coin flip.",
                "Nothing on the {category}. {player} will feel that later.",
                "{player} sacrifices the {category}. The dice send their regards.",
                "Zero there, {player}. Chalk it up to confidence.",
                "{player} lets the {category} go. Future {player} is furious.",
                "A goose egg on the {category}. {player} plays chess. Badly.",
                "{player} scratches the {category}. Living the dream, minus points.",
                "Zero. {player} decided the {category} was optional. It wasn't.",
                "{player} clears the {category} at nothing. Efficient way to lose.",
                "A scratch. {player}, the {category} deserved better.",
                "{player} takes zero on the {category}. Somewhere a coach sighs.",
                "Nothing on the {category}. {player} is manifesting a comeback. Good luck.",
                "{player} zeroes it. The {category} will be missed. By the scoreboard.",
                "A scratch, {player}. Bold to just give points away.",
                "{player} passes on the {category}. Points are for other people, apparently.",
                "Zero on the {category}. {player} is really committing to the bit.",
                "{player} zeroes the {category}. Somewhere, a plan is unraveling.",
                "Nothing on the {category}. {player} calls that strategy. We call it Tuesday.",
                "{player} scratches. The {category} deserved a better owner.",
                "A zero on the {category}. {player} is playing with fire, and losing.",
                "{player} gives up the {category}. The scoreboard says nothing. Loudly.",
                "Zero. {player} decided points were optional this turn.",
                "{player} scratches the {category}. Bold to just donate a box.",
                "Nothing there. {player} is manifesting better dice. Good luck.",
                "{player} takes a zero. The comeback narrative continues to struggle.",
                "A scratch on the {category}. {player} is building character. Only character.",
                "{player} clears the {category} at nothing. Efficient, in the worst way.",
                "Zero on the {category}. {player} will explain the reasoning later. At length.",
                "{player} lets the {category} go. Future {player} sends complaints.",
                "A goose egg. {player} makes the hard choice. The wrong one, probably.",
                "{player} scratches the {category}. The dice offered nothing and {player} agreed.",
                "Zero there. {player} keeps the streak of interesting decisions alive.",
                "{player} passes on the {category}. Points are apparently beneath them.",
                "A blank on the {category}. {player} is committed to the aesthetic.",
                "{player} zeroes it. That box is gone and so is the plan.",
                "Nothing on the {category}, {player}. It happens. It happens a lot."
            ]
        ]
    )
}
