import Foundation

extension CommentaryPersonality {
    static let snarky = CommentaryPersonality(
        id: "snarky",
        displayName: "Snarky",
        blurb: "The deadpan wit — dry, playful, mock-dramatic. Ribs the roll, never the person.",
        prosody: CommentaryProsody(rate: 0.48, pitchMultiplier: 0.98, preUtteranceDelay: 0.20, postUtteranceDelay: 0.15),
        previewLine: "Five of a kind. The dice clearly have a favorite tonight. Suspicious.",
        lines: [
            .yatzyRolled: [
                "A Yatzy. {player} is going to be insufferable now.",
                "Five of a kind. The dice clearly like {player} better than the rest of us.",
                "Oh good, a Yatzy. {player} will remind everyone of this for weeks.",
                "{player} rolls a Yatzy. Statistically rude.",
                "Five matching dice. {player} did that on purpose, apparently.",
                "A Yatzy for {player}. The rest of the table would like to lodge a complaint.",
                "Well. {player} just peaked. Downhill from here.",
                "Five of a kind. {player}, save some luck for the others.",
                "A Yatzy. Somewhere a probability textbook is crying.",
                "{player} lands the Yatzy and acts like it was skill.",
                "Fifty points, and {player} definitely called it. Sure.",
                "Five dice, one face. {player} is officially unbearable.",
                "A Yatzy. {player} would like everyone to remember this moment forever.",
                "The dice rolled over for {player}. Traitors.",
                "{player} gets a Yatzy. The others are handling it beautifully. Not.",
                "Five of a kind. {player} earned it, or bribed the dice. Unclear.",
                "Congratulations to {player}, and condolences to everyone else.",
                "A Yatzy. Cool, cool, totally fine, no notes.",
                "{player} rolls five of a kind and the group chat will never recover.",
                "Well rolled, {player}. Nobody's jealous. Everyone's jealous.",
                "A Yatzy for {player}. The dice have chosen a favorite and it isn't you, reader."
            ],
            .yahtzeeBonusEarned: [
                "Another Yatzy. {player} is just showing off now.",
                "A second five of a kind. {player}, leave some for the class.",
                "Oh, a bonus Yatzy. {player} definitely needed the extra hundred.",
                "{player} rolls another one. The dice have a clear agenda.",
                "Two Yatzys. {player} is writing a book about it as we speak.",
                "Bonus hundred for {player}. The others are thrilled. Visibly.",
                "Again? {player}, this is getting embarrassing for everyone else.",
                "A repeat Yatzy. {player} has clearly made a deal with someone.",
                "{player} adds a hundred. Somewhere, math is offended.",
                "Another five of a kind. {player} is not even trying to be humble.",
                "Two in a game. {player} will mention this at the funeral.",
                "Bonus Yatzy. {player}, the dice are practically autographing themselves.",
                "{player} does it again. The table's morale is doing great. Not.",
                "A second hundred. {player} is basically cheating with permission.",
                "Encore Yatzy for {player}. Nobody asked, but here we are.",
                "{player} rolls another. The other players have questions.",
                "Two Yatzys. {player} is one away from being challenged to a duel.",
                "Bonus points for {player}. Skill, luck, or witchcraft. Pick one.",
                "Another one. {player} is speedrunning smugness.",
                "{player} stacks a hundred. The dice know exactly what they're doing.",
                "A repeat Yatzy. Truly inspiring. Truly annoying. Both, {player}."
            ],
            .winnerDeclared: [
                "{winner} wins. Everyone act surprised.",
                "And the winner is {winner}, who will absolutely bring this up again.",
                "{winner} takes it by {margin}. {runnerUp} is fine. {runnerUp} is totally fine.",
                "Congratulations, {winner}. The dice apologize to everyone else.",
                "{winner} wins with {score}. A number they will have tattooed by morning.",
                "It's over. {winner} won, and now we all have to hear about it.",
                "{winner} on top. {runnerUp}, so close, which is somehow worse.",
                "Winner, {winner}. Please contain your gloating. You won't.",
                "{winner} takes it. The rematch demands are already forming.",
                "{winner} wins by {margin}. Rounding up, that's a lot.",
                "And {winner} closes it out. Humble in victory. Kidding. Not humble.",
                "{winner} first. The dice have spoken and they were extremely biased.",
                "{score} for the win. {winner} peaked at the perfect time. Annoying.",
                "{winner} wins. {runnerUp} led for a while, which they'll mention forever.",
                "Victory for {winner}. Everyone clap, some of you mean it.",
                "{winner} takes the crown. It's a paper one, but still.",
                "Game over. {winner} won. Physics remains undefeated.",
                "{winner} on top by {margin}. Screenshot it, they will.",
                "And that's a win for {winner}. The trash talk starts in three, two, one.",
                "{winner} wins. {runnerUp} played great and lost anyway. Delightful.",
                "Your champion, {winner}, who definitely won't rig the next one. Probably."
            ],
            .winnerTie: [
                "A tie. Nobody wins, everybody argues.",
                "{winner} tied at {score}. A rematch is now legally required.",
                "It's a draw. {winner} will each claim they really won.",
                "{winner} finish level. The universe declines to pick a favorite.",
                "A tie. {winner}, please resolve this outside.",
                "Deadlocked at {score}. {winner} both insufferable, equally.",
                "{winner} tied. The dice took the coward's way out.",
                "A draw. {winner} share the trophy, which is one trophy. Good luck.",
                "{winner} match exactly. Somebody count again, surely.",
                "It's even. {winner} both win, which means nobody gets to gloat properly.",
                "A tie. {winner}, this is the worst possible outcome for peace.",
                "{winner} at {score} apiece. Sudden death is the only civilized option.",
                "Level game. {winner} will litigate this for years.",
                "A tie. Congratulations to {winner}, and to chaos."
            ],
            .upperBonusEarned: [
                "{player} got the upper bonus. Someone read the rules.",
                "Thirty-five bonus points for {player}. The nerds call this strategy.",
                "{player} cleared sixty-three. Suspiciously competent.",
                "Upper bonus for {player}. Playing to win, are we.",
                "{player} banks the thirty-five. Look who did their homework.",
                "The bonus goes to {player}, who apparently planned ahead. Show-off.",
                "{player} hit sixty-three. That's a lot of ones and twos of patience.",
                "Bonus secured. {player} is taking this seriously now.",
                "{player} gets thirty-five for good behavior. Rare.",
                "Upper bonus, {player}. The tortoise strategy pays off.",
                "{player} managed the boring section and got paid. Fine, well done.",
                "Thirty-five points for {player}'s spreadsheet energy.",
                "{player} cleared the threshold. Somebody's competitive.",
                "The bonus lands with {player}, who definitely counted first.",
                "{player} earns thirty-five. The upper section's revenge.",
                "Upper bonus for {player}. Discipline. Gross.",
                "{player} hit sixty-three exactly, probably on purpose. Menace.",
                "Thirty-five bonus. {player} is playing chess, we're playing checkers.",
                "{player} got the bonus and a smug little nod, no doubt.",
                "Bonus points, {player}. The math homework paid off after all."
            ],
            .yatzyScratched: [
                "{player} scratched the Yatzy. Bold. Reckless. Both.",
                "A zero on the Yatzy. {player} lives dangerously.",
                "{player} just poisoned the box. No takebacks, no bonus, no mercy.",
                "And {player} scratches the Yatzy. Future self will love that.",
                "Zero on the fifty-pointer. {player} plays fast and loose.",
                "{player} sacrifices the Yatzy. The dice noted your address.",
                "A scratch. {player} said no thank you to a hundred future points.",
                "{player} zeroes the Yatzy box. Chaos reigns.",
                "{player} scratched it. Somewhere a strategy guide fainted.",
                "Zero on the Yatzy. {player} is either a genius or not. Not.",
                "{player} closes the bonus door and throws away the key.",
                "A poisoned box, courtesy of {player}. Live footage of a decision.",
                "{player} scratches the Yatzy. The other players say nothing. They're thrilled.",
                "Zero. {player} gambled the fifty and the house always remembers.",
                "{player} just gave up the Yatzy. Confidence or panic. We'll never know.",
                "The Yatzy box, zeroed by {player}. Fortune favors the... not this.",
                "{player} scratched it. Somewhere, a math teacher wept.",
                "A zero on the Yatzy. {player} enjoys living without a safety net.",
                "{player} poisons the box. The dice will absolutely hold a grudge.",
                "Scratched. {player}, that's going to be a fun one to explain later."
            ],
            .bigTurn: [
                "{player} scores a {category} for {value}. Look at that, actual competence.",
                "A {category} worth {value}. {player} is trying now. Concerning.",
                "{player} banks {value} on the {category}. Suspiciously well played.",
                "{value} points on the {category}. {player} means business, apparently.",
                "{player} lands the {category}. {value}. Beginner's luck? Rude either way.",
                "A big {category} from {player}. The rest of you might want to wake up.",
                "{player} takes {value}. That {category} won't shut up about itself.",
                "{category} for {value}. {player} is making the rest look decorative.",
                "{player} scores {value}. The dice are cooperating a little too eagerly.",
                "A {category}, {value} points. {player} found the good roll. Hoarding, really.",
                "{player} banks the {category}. {value}. Someone's feeling themselves.",
                "{value} on the {category}. {player}, save some points for the others.",
                "{player} completes the {category}. {value}. Textbook. Insufferably so.",
                "A {category} worth {value}. {player} is climbing. Ugh, effective.",
                "{player} takes {value}. The {category} gods smiled. Favoritism, clearly.",
                "{value} points, {player}. That {category} is going straight to your head.",
                "{player} scores the {category}. {value}. Fine. That was good. Don't gloat.",
                "A tidy {category} for {value}. {player} is peaking suspiciously well.",
                "{player} banks {value}. The {category} came easy. Some people have all the luck.",
                "{value} on the {category}. {player} is quietly running away with this. Quietly."
            ],
            .leadChange: [
                "{leader} takes the lead. {runnerUp} did not care for that.",
                "New leader, {leader}. The peace was nice while it lasted.",
                "{leader} passes {runnerUp}. Betrayal, honestly.",
                "And {leader} grabs the lead. {runnerUp} is fine. {runnerUp} is seething.",
                "{leader} in front now. {runnerUp} would like a word.",
                "Lead change. {leader} on top, and loving it too much.",
                "{leader} overtakes {runnerUp}. The alliance is over.",
                "{leader} takes first. {runnerUp}, that spot was warm.",
                "{leader} leads now. Screenshot it, it won't last.",
                "{runnerUp} loses the lead to {leader}. Awkward at the table.",
                "{leader} muscles ahead. {runnerUp} is drafting a strongly worded rebuttal.",
                "New number one, {leader}. {runnerUp} has entered their villain arc.",
                "{leader} takes the lead. Enjoy the view, it's a rental.",
                "{leader} ahead of {runnerUp} now. The tension is delicious.",
                "{leader} steals first. {runnerUp} remembers this.",
                "And {leader} leads. {runnerUp} would like to speak to the dice's manager.",
                "{leader} up front. {runnerUp} pretending not to mind. Failing.",
                "{leader} takes over. {runnerUp}, welcome to second.",
                "{leader} leads now, briefly, probably, we'll see.",
                "{leader} passes {runnerUp}. Somewhere a friendship strains."
            ],
            .turnStart: [
                "{player}'s turn. Try to make it count.",
                "Up next, {player}. No pressure. Some pressure.",
                "{player}, the dice await your questionable decisions.",
                "It's {player}'s turn. Let's see the strategy. Or lack of.",
                "{player} takes the dice. Good luck, you'll need it.",
                "Over to {player}. The bar is low, clear it.",
                "{player}, your moment to disappoint the dice.",
                "{player}'s up. Fingers crossed, everyone.",
                "Now {player}. Whenever the confidence arrives.",
                "{player} rolls next. This should be interesting. Or not.",
                "{player}, the tray is yours. Handle it.",
                "Turn's yours, {player}. Don't overthink it, you will.",
                "{player} steps up. Bold of you.",
                "Here's {player}, live and probably unprepared.",
                "{player}'s turn. The dice have low expectations.",
                "Go on then, {player}. Amaze us. Or don't.",
                "{player} takes over. History is watching, sort of.",
                "{player}, roll the dice and pray.",
                "Up you go, {player}. We believe in you. Mostly.",
                "It's {player}'s turn. Set your expectations accordingly."
            ],
            .categoryScored: [
                "{player} takes {value} on the {category}. Bold choice. We'll allow it.",
                "{value} for the {category}. {player} is playing it safe. Yawn.",
                "{player} scores {value} on the {category}. Riveting stuff.",
                "The {category} for {value}. {player} shrugs and moves on.",
                "{value} on the {category}. {player}. Groundbreaking.",
                "{player} fills the {category}. {value}. Adequate.",
                "That's {value} on the {category}, {player}. The crowd is stunned. Not.",
                "{player} banks {value} on the {category}. Living on the edge, clearly.",
                "A {category} for {value}. {player} keeps the dream barely alive.",
                "{value} on the {category}. {player}, you had to score somewhere.",
                "{player} takes the {category}. {value}. Sure, why not.",
                "{value} for {player} on the {category}. Every little bit helps. Barely.",
                "The {category}, {value}. {player} settles.",
                "{player} logs {value} on the {category}. The suspense is underwhelming.",
                "{value} on the {category}. {player} plays the percentages. Cowardly.",
                "{player} scores the {category} for {value}. History will not remember this.",
                "A {value} on the {category}. Points are points, {player}. Allegedly.",
                "{player} takes {value} on the {category} and calls it a day.",
                "{value} on the {category}. That'll... do something, {player}.",
                "The {category} for {value}. {player} soldiers on. Barely."
            ],
            .categoryScratched: [
                "{player} scratches the {category}. That'll haunt them.",
                "Zero on the {category}. {player} had bigger plans, clearly.",
                "{player} takes a zero. Strategic. Allegedly.",
                "A scratch on the {category}. {player} is gambling with the math.",
                "{player} zeroes the {category}. Bold. Or panicked. Coin flip.",
                "Nothing on the {category}. {player} will feel that later.",
                "{player} sacrifices the {category}. The dice send their regards.",
                "Zero there, {player}. Chalk it up to confidence.",
                "{player} lets the {category} go. Future {player} is furious.",
                "A goose egg on the {category}. {player} plays chess. Badly.",
                "{player} scratches the {category}. Living the dream, minus points.",
                "Zero. {player} decided the {category} was optional. It wasn't.",
                "{player} clears the {category} at nothing. Efficient way to lose.",
                "A scratch. {player}, the {category} deserved better.",
                "{player} takes zero on the {category}. Somewhere a coach sighs.",
                "Nothing on the {category}. {player} is manifesting a comeback. Good luck.",
                "{player} zeroes it. The {category} will be missed. By the scoreboard.",
                "A scratch, {player}. Bold to just give points away.",
                "{player} passes on the {category}. Points are for other people, apparently.",
                "Zero on the {category}. {player} is really committing to the bit."
            ]
        ]
    )
}
