import Foundation
import SyLibCommentary

extension CommentaryPersonality where Kind == CommentaryEventKind {
    static let zen = CommentaryPersonality(
        id: "zen",
        displayName: "Zen",
        blurb: "The mindful narrator — calm, present-tense, gently wry serenity.",
        prosody: CommentaryProsody(rate: 0.42, pitchMultiplier: 0.96, preUtteranceDelay: 0.35, postUtteranceDelay: 0.30),
        previewLine: "Five dice, one mind. Everything arrives in its own time.",
        lines: [
            "yatzyRolled": [
                "Five dice, one mind. {player} finds the Yatzy.",
                "Everything settles into place for {player}. A Yatzy.",
                "{player} rolls, and the dice agree. Yatzy.",
                "Stillness, then five of a kind. Well done, {player}.",
                "The path opened for {player}. A quiet fifty.",
                "All five aligned. {player} receives a Yatzy.",
                "{player} lets go, and the dice arrive together.",
                "A moment of harmony. Five faces, one for {player}.",
                "No forcing, only flow. {player} lands the Yatzy.",
                "{player} breathes, and the dice fall as one.",
                "Five as one. {player} meets the Yatzy.",
                "The dice found their center for {player}.",
                "What is meant to arrive, arrives. {player}, a Yatzy.",
                "{player} rolls with an open hand. Five of a kind.",
                "Presence rewarded. {player} takes the fifty.",
                "Calm hands, five faces. A Yatzy for {player}.",
                "{player} and the dice, briefly, in perfect agreement.",
                "The moment ripened. {player} gathers a Yatzy.",
                "Five dice at rest, all the same. Peace, and a Yatzy, for {player}.",
                "{player} did nothing extra, and everything worked. Yatzy.",
                "A small miracle on the table. {player}, five of a kind.",
                "The dice arrive together. {player}, a Yatzy.",
                "{player} holds nothing tightly, and everything lands. Yatzy.",
                "Five faces, one answer. {player} receives it.",
                "Nothing was forced. {player} rolls five of a kind.",
                "{player} opens a hand, and fifty points rest in it.",
                "The tray goes quiet. Five alike, for {player}.",
                "{player} arrives exactly where the dice were going. Yatzy.",
                "A rare stillness. {player} finds all five in agreement.",
                "{player} rolls without wanting. The Yatzy comes anyway.",
                "Five dice, no argument. {player} takes the fifty.",
                "The pattern completes itself. Yatzy, {player}.",
                "{player} watches five faces agree. That is a Yatzy.",
                "Chance and calm meet here. {player}, five of a kind.",
                "{player} lets the dice decide, and they decide generously.",
                "One face, five times. A gift for {player}.",
                "The roll resolves into a single shape. {player} has a Yatzy.",
                "{player} sits with the moment. Fifty points sit with them.",
                "Nothing hurried, nothing held. {player} rolls a Yatzy.",
                "The table falls still for {player}. Five of a kind.",
                "{player} receives what the dice offered. A Yatzy.",
                "Simple, complete, whole. {player} takes the fifty."
            ],
            "yatzyBonusEarned": [
                "Again, the dice align for {player}. A hundred more, received quietly.",
                "The flow continues. {player} finds another five of a kind.",
                "What began, continues. {player} takes the bonus.",
                "{player} stays present, and the dice return. A hundred points.",
                "No grasping, only more. {player} earns the bonus Yatzy.",
                "The stream keeps flowing for {player}. Another hundred.",
                "{player} rolls again, and again it is five as one.",
                "Abundance, without effort. {player} gathers a hundred.",
                "The moment repeats itself gently. {player}, a bonus Yatzy.",
                "{player} remains calm, and the dice remain kind. Plus one hundred.",
                "Once more the faces agree. Well done, {player}.",
                "{player} does not chase it, and it comes anyway.",
                "The wave carries {player} a little further. A hundred more.",
                "Stillness, then five of a kind. Twice now, {player}.",
                "{player} accepts the bonus as it is given.",
                "What is flowing does not stop for {player}. Another hundred.",
                "Balance holds. {player} rolls a second Yatzy.",
                "{player} breathes, and a hundred points arrive.",
                "The dice keep their promise to {player}. Bonus Yatzy.",
                "Again, effortless. {player} takes the hundred.",
                "{player} and fortune, still walking together.",
                "The pattern returns to {player}. Another hundred.",
                "{player} rolls again, and again the dice agree.",
                "Twice now. {player} accepts a second Yatzy.",
                "Nothing is being chased. Still it comes. {player}, plus one hundred.",
                "{player} holds the same calm, and receives the same gift.",
                "The current has not turned. {player} takes another hundred.",
                "Repetition without effort. {player}, a bonus Yatzy.",
                "{player} stays soft, and the dice stay kind.",
                "Again, five as one. Well met, {player}.",
                "The bonus arrives quietly for {player}. A hundred points.",
                "{player} does not question it. Another Yatzy.",
                "Fortune settles twice on {player}. Received, not seized.",
                "A second alignment. {player} adds a hundred.",
                "{player} lets the good roll be good. Bonus Yatzy.",
                "What flows once may flow again. {player}, plus one hundred.",
                "The dice repeat their kindness to {player}.",
                "{player} takes the hundred without leaning forward.",
                "Twice the same shape. {player} sits with it.",
                "Good fortune lingers near {player}. A bonus Yatzy.",
                "{player} rolls a second five of a kind. Nothing needs saying.",
                "Another hundred, held lightly by {player}."
            ],
            "winnerDeclared": [
                "The game rests. {winner} arrives at the top, with {score}.",
                "All turns complete. {winner} holds the highest score.",
                "{winner} finishes gently ahead. {score} points.",
                "The path led here. {winner}, this game is yours.",
                "Nothing left to roll. {winner} settles into first.",
                "{winner} and {runnerUp} both played well. Tonight, {winner} leads.",
                "The dice are still. {winner} carries the game, by {margin}.",
                "Completion. {winner} takes the win, softly.",
                "{winner} reaches the summit without hurry. {score}.",
                "The final rest. {winner} on top.",
                "A good game, well played by all. {winner} first.",
                "{winner} closes the circle with {score}.",
                "Effort and ease, in balance. {winner} wins.",
                "The game exhales. {winner}, the winner.",
                "{winner} arrives where the game was going. First place.",
                "All is scored. {winner} holds the lead, {score}.",
                "{runnerUp} pressed close. {winner} kept the calm, and the win.",
                "{winner} finishes present and steady. The game is theirs.",
                "Peace on the table. {winner} takes it.",
                "The last die settles. {winner} wins, by {margin}.",
                "Well played, everyone. {winner}, the quiet victor.",
                "The scores come to rest. {winner} sits highest, at {score}.",
                "{winner} finishes ahead by {margin}. Gently done.",
                "Every box is full. {winner} takes the game.",
                "The last turn passes. {winner} holds first.",
                "{winner} and {runnerUp} walked the same road. {winner} arrives first.",
                "Nothing more to roll. {winner} wins, with {score}.",
                "{winner} carries the game home, unhurried.",
                "The board is complete. {winner} on top.",
                "{score} points, and a quiet win for {winner}.",
                "{winner} leads at the end, by {margin}. Well played.",
                "The dice rest. {winner} is the winner.",
                "All scores settle. {winner} above {runnerUp}.",
                "{winner} finishes the game they were always finishing.",
                "A soft conclusion. {winner} takes it with {score}.",
                "{winner} holds the highest number. That is all it is.",
                "The game closes around {winner}. First place.",
                "{runnerUp} played beautifully. {winner} played a little more so.",
                "{winner} wins. The table exhales.",
                "Nothing left undone. {winner}, {score}.",
                "{winner} steps into first and stays. Well played.",
                "The final rest belongs to {winner}."
            ],
            "winnerTie": [
                "Two paths, one summit. {winner} arrive together, at {score}.",
                "A tie. {winner} share the game, and the peace.",
                "No one ahead, no one behind. {winner}, level at {score}.",
                "Balance itself. {winner} finish as equals.",
                "The game holds no single winner. {winner} share it.",
                "{winner} meet at the same place. {score} each.",
                "Perfect symmetry. {winner} tied.",
                "Neither above the other. {winner} rest as one.",
                "A shared summit for {winner}. {score}.",
                "The dice divided nothing. {winner} tie.",
                "Equal effort, equal end. {winner}, together at {score}.",
                "{winner} arrive side by side. A gentle tie.",
                "No division tonight. {winner} share the win.",
                "Stillness, and a tie. {winner}, both first.",
                "Two arrive as one. {winner}, both at {score}.",
                "The game declines to choose. {winner} tie.",
                "{winner} finish exactly together. {score}.",
                "Equal, and easy about it. {winner} share the game.",
                "No one ahead. {winner} rest at {score}.",
                "A tie, which is its own kind of ending. {winner}.",
                "{winner} match, point for point. Nothing to divide.",
                "The scores mirror each other. {winner}, tied.",
                "Both first, neither second. {winner} at {score}.",
                "{winner} arrive holding the same number.",
                "Balance closes the game. {winner} tied.",
                "There is no winner alone. {winner} share it.",
                "A quiet draw for {winner}. {score} each.",
                "The game ends level. {winner}, together."
            ],
            "upperBonusEarned": [
                "Patience rewarded. {player} earns the upper bonus.",
                "{player} tended the small numbers, and the bonus arrived.",
                "Steady work brings its gift. {player}, thirty-five points.",
                "{player} reaches sixty-three, and the bonus follows.",
                "Nothing rushed. {player} gathers the upper bonus.",
                "The quiet effort pays. {player} takes the thirty-five.",
                "{player} kept to the path, and the path gave back.",
                "Small stones build the wall. {player} earns the bonus.",
                "{player} arrives at sixty-three, gently. Bonus received.",
                "The upper section, complete for {player}. Thirty-five.",
                "{player} planted early and harvests now.",
                "Attention to the little things. {player}, the bonus is yours.",
                "{player} let the numbers add themselves. Bonus earned.",
                "Diligence, made visible. {player} takes the thirty-five.",
                "{player} crosses the threshold with ease. Bonus.",
                "The upper bonus settles on {player}, well deserved.",
                "{player} kept the balance up top, and it held. Bonus.",
                "Slow and sure, {player} claims the thirty-five.",
                "{player} finishes the upper work in peace.",
                "Sixty-three, and beyond. {player} receives the bonus.",
                "{player} tended the ones and twos. Now the bonus.",
                "Sixty-three, reached without hurry. {player}, thirty-five.",
                "{player} finishes the small work, and it repays them.",
                "The upper section settles kindly on {player}. Bonus earned.",
                "{player} did not skip the quiet numbers. Thirty-five points.",
                "Patience has a number. For {player}, it is thirty-five.",
                "{player} crosses the line gently. Upper bonus.",
                "Steady hands up top. {player} takes the bonus.",
                "{player} gathers thirty-five for careful work.",
                "The threshold passes beneath {player}. Bonus received.",
                "{player} built it one face at a time. Now the bonus.",
                "Nothing dramatic, only enough. {player}, thirty-five.",
                "{player} keeps the upper section whole. Bonus counted.",
                "A small discipline, well rewarded. {player}.",
                "{player} arrives at sixty-three and rests. Thirty-five.",
                "The upper bonus finds {player}, as it should.",
                "{player} paid attention early. The bonus is the thanks.",
                "Thirty-five points, quietly added to {player}.",
                "{player} completes the top half in balance. Bonus.",
                "What was tended has grown. {player} takes the bonus."
            ],
            "yatzyScratched": [
                "{player} releases the Yatzy, and takes nothing. Sometimes we let go.",
                "A zero on the Yatzy. {player} chooses to release the fifty.",
                "{player} scratches the box. What is empty stays empty. It is enough.",
                "Not every door opens. {player} sets the Yatzy aside.",
                "{player} accepts a zero. Attachment released.",
                "The Yatzy passes by. {player} does not grasp it.",
                "{player} lets the fifty go without regret. Or with some. That is honest.",
                "A scratch. {player} makes peace with the empty box.",
                "{player} closes the Yatzy quietly. No bonus will come. So it is.",
                "Sometimes the roll asks for a sacrifice. {player} gives the Yatzy.",
                "{player} takes the zero, and breathes. The game continues.",
                "What could have been fifty becomes zero. {player} accepts it.",
                "{player} scratches the box. Loss, held lightly.",
                "The Yatzy is released by {player}. Onward, gently.",
                "{player} lets it be zero. There is freedom in that too.",
                "No Yatzy this game for {player}. The board narrows. Notice it.",
                "{player} surrenders the fifty. A small letting-go.",
                "The box empties by choice. {player} moves on.",
                "{player} scratches the Yatzy, and the mind stays calm.",
                "Zero, chosen freely by {player}. Even loss can be clean.",
                "{player} lets the Yatzy be nothing. That is allowed.",
                "The box closes empty. {player} does not mind. Much.",
                "{player} gives up the fifty and keeps the calm.",
                "A zero, taken on purpose. {player} moves on.",
                "{player} releases what was never certain. The Yatzy, gone.",
                "Some things are set down. {player} sets down the Yatzy.",
                "{player} chooses the empty box. The game continues either way.",
                "No fifty. {player} accepts the shape of this game.",
                "{player} scratches the Yatzy. Little is lost, except the fifty.",
                "The Yatzy passes through {player}'s hands unheld.",
                "{player} takes zero, and the mind does not follow it.",
                "An empty box, quietly chosen by {player}.",
                "{player} closes the door and stays peaceful in the room.",
                "The bonus will not come now. {player} knew that.",
                "{player} scratches the fifty. Let it go easily.",
                "Zero on the Yatzy. {player} makes it a decision, not a wound.",
                "{player} surrenders the big box. The board is simpler now.",
                "What is empty is also finished. {player} scratches the Yatzy.",
                "{player} lays the Yatzy down. No bonus follows. So be it.",
                "A clean zero for {player}. Even this can be peaceful."
            ],
            "bigTurn": [
                "{player} completes the {category}. {value} points, arriving in order.",
                "The pattern reveals itself. {player}, a {category} for {value}.",
                "{player} lets the dice fall into place. {category}, {value}.",
                "Form emerges. {player} scores {value} on the {category}.",
                "{player} finds the {category}. {value}, without strain.",
                "A shape completed. {player} takes {value}.",
                "{player} gathers the {category}, worth {value}. Well seen.",
                "The dice arrange themselves for {player}. {category}, {value}.",
                "{player} scores the {category}. {value} points, quietly earned.",
                "Everything in sequence. {player}, {value} on the {category}.",
                "{player} sees the pattern and takes it. {value}.",
                "A {category} for {player}. {value}, received.",
                "{player} completes the shape. {value} points.",
                "The right pieces, in the right places. {player}, {value}.",
                "{player} claims the {category}, worth {value}. Steady work.",
                "Balance on the board. {player} scores {value}.",
                "{player} finishes the {category} with a calm hand. {value}.",
                "Order from the roll. {player}, {value} points.",
                "{player} takes the {category}. {value}, no fuss.",
                "The dice cooperate. {player} banks {value} on the {category}.",
                "{player} finds the {category}. {value} points, gently taken.",
                "The dice fall into shape. {player}, {value}.",
                "{player} recognizes the {category} and takes it. {value}.",
                "A good turn, unforced. {player} scores {value}.",
                "The {category} appears for {player}. {value} points.",
                "{player} accepts the {category}. {value}, no more needed.",
                "Order arrives. {player} banks {value}.",
                "{player} takes the {category} as it was offered. {value}.",
                "{value} on the {category}. {player} does not celebrate loudly.",
                "The roll made sense. {player}, {category}, {value}.",
                "{player} scores {value} and lets the turn close.",
                "A whole shape, quietly. {player} takes {value}.",
                "{player} completes the {category}. {value} points settle in.",
                "The pieces met. {player} scores the {category} for {value}.",
                "{player} sees it clearly and takes {value}.",
                "Nothing wasted. {player}, {value} on the {category}.",
                "{player} places the {category} and rests. {value}.",
                "A generous roll, calmly received. {player}, {value}.",
                "{player} takes {value} on the {category}. The board grows.",
                "The {category} completes itself for {player}. {value}."
            ],
            "leadChange": [
                "The lead shifts, softly. {leader} moves ahead of {runnerUp}.",
                "{leader} rises to the front. The game breathes and changes.",
                "Nothing stays fixed. {leader} now leads.",
                "{leader} steps ahead of {runnerUp}. The current turns.",
                "The tide comes in for {leader}. First place, for now.",
                "{leader} takes the lead, and holds it lightly.",
                "Positions flow. {leader} ahead, {runnerUp} close.",
                "{leader} moves forward. All places are temporary.",
                "The front belongs to {leader} in this moment.",
                "{leader} passes {runnerUp}. The river keeps moving.",
                "A gentle shift. {leader} now leads.",
                "{leader} rises without pushing. First place.",
                "The lead changes hands, calmly. {leader} in front.",
                "{leader} ahead now. {runnerUp} need not worry. It flows both ways.",
                "{leader} takes the top, for as long as it lasts.",
                "The game turns toward {leader}. First place.",
                "{leader} steps into the lead, quietly.",
                "Ahead and behind trade places. {leader} leads.",
                "{leader} moves to first. Nothing is settled yet.",
                "The lead rests with {leader} now. Watch it change again.",
                "{leader} moves to the front. Nothing is permanent.",
                "The order rearranges. {leader} leads now.",
                "{leader} passes quietly ahead of {runnerUp}.",
                "First place changes hands. {leader} holds it.",
                "{leader} steps forward. {runnerUp} steps back. Both fine.",
                "A shift, without force. {leader} in front.",
                "{leader} takes the lead and does not clutch it.",
                "The current favors {leader} now.",
                "{leader} leads. Positions are only weather.",
                "{runnerUp} falls behind. {leader} rises. It goes both ways.",
                "{leader} moves into first, softly.",
                "The board turns. {leader} on top for now.",
                "{leader} is ahead. This too will change.",
                "Nothing was taken. {leader} simply arrived first.",
                "{leader} passes {runnerUp}. Notice it, then let it go.",
                "The lead settles with {leader}, for a while.",
                "{leader} rises without effort. First place.",
                "{runnerUp} led. Now {leader} does. Both were true.",
                "{leader} leads the game. The game is not over.",
                "A quiet change at the top. {leader} in front."
            ],
            "turnStart": [
                "{player}'s turn. Breathe, then roll.",
                "The dice come to {player}.",
                "It is {player}'s moment now.",
                "{player} takes the dice, gently.",
                "Whenever you're ready, {player}.",
                "The turn passes to {player}.",
                "{player}, the table is yours.",
                "Now {player}. No hurry.",
                "{player} arrives at their turn.",
                "The dice rest, waiting for {player}.",
                "{player}, take your time.",
                "A new turn opens for {player}.",
                "{player} steps in, calm.",
                "The moment is {player}'s.",
                "{player}, roll when the mind is still.",
                "Over to {player}, softly.",
                "{player} receives the dice.",
                "Presence, please, {player}. Your turn.",
                "{player}'s turn begins.",
                "The dice belong to {player} now.",
                "{player}, the dice are ready when you are.",
                "The turn opens for {player}.",
                "{player}, begin whenever it feels right.",
                "Now it is {player} at the tray.",
                "{player} receives the turn.",
                "A fresh roll waits for {player}.",
                "{player}, settle first. Then roll.",
                "The dice pass gently to {player}.",
                "{player}'s turn arrives.",
                "Take a breath, {player}.",
                "{player} steps up without hurry.",
                "The table waits calmly for {player}.",
                "{player}, nothing is urgent.",
                "Your moment, {player}.",
                "{player} comes to the dice.",
                "The turn belongs to {player} now.",
                "{player}, roll as you are.",
                "Softly now, {player}.",
                "{player} begins.",
                "The dice rest in {player}'s hands."
            ],
            "categoryScored": [
                "{player} takes {value} on the {category}. Onward.",
                "The {category}, filled. {player}, {value}.",
                "{player} places {value} on the {category}, calmly.",
                "A quiet {value} on the {category}. {player}.",
                "{player} scores the {category}. {value} points.",
                "{value} added to the {category}, without fuss. {player}.",
                "{player} completes the {category}. {value}.",
                "The {category} grows the board by {value}. {player}.",
                "{player} sets the {category} at {value}, gently.",
                "{category}, {value}. {player} moves on.",
                "{player} takes what the roll offered. {category}, {value}.",
                "A small step on the {category}. {player}, {value}.",
                "{player} fills the {category}. {value}.",
                "{value} on the {category}, received. {player}.",
                "{player} takes the {category}. {value}. Enough.",
                "The {category} settles at {value}. {player}.",
                "{player} adds {value} on the {category} and lets it be.",
                "{value} for {player} on the {category}. Enough for now.",
                "{player} places the {category}. {value}.",
                "A steady {value} on the {category}. {player}.",
                "{player} sets {value} into the {category}.",
                "The {category} receives {value}. {player}.",
                "{player} scores {value} and the turn closes.",
                "{value} on the {category}, taken as it came. {player}.",
                "{player} completes the {category} quietly. {value}.",
                "A modest {value} on the {category} for {player}.",
                "{player} accepts the {category}. {value} points.",
                "The board grows by {value}. {player}.",
                "{player} marks the {category} at {value}. Onward.",
                "{value} for the {category}. Nothing more is asked, {player}.",
                "{player} lets the {category} take {value}.",
                "A steady turn. {player}, {value} on the {category}.",
                "{player} fills a box and moves along. {category}, {value}.",
                "{value} settles into the {category}. {player}.",
                "{player} takes the {category} at {value}. It is enough.",
                "The turn ends simply. {player}, {value}.",
                "{player} adds {value} without ceremony.",
                "{category} closed at {value}. Well done, {player}.",
                "{player} places {value} and lets go.",
                "Small progress, honestly earned. {player}, {value}."
            ],
            "categoryScratched": [
                "{player} releases the {category}. Zero. It is fine.",
                "A zero on the {category}. {player} lets it pass.",
                "{player} sets the {category} aside, empty.",
                "Not this one. {player} scratches the {category}.",
                "{player} takes nothing, and takes it well.",
                "The {category} goes to zero. {player} moves on.",
                "{player} lets the {category} be empty. No harm.",
                "A quiet zero for {player} on the {category}.",
                "{player} releases the {category}. Onward.",
                "Nothing here. {player} accepts the {category} as zero.",
                "{player} scratches gently. {category}, zero.",
                "Some rolls ask for nothing. {player} scratches the {category}.",
                "{player} lets the {category} go without a fight.",
                "A zero, chosen. {player} clears the {category}.",
                "{player} makes peace with an empty {category}.",
                "The {category} rests at zero. {player} continues.",
                "{player} gives up the {category}, calmly.",
                "Not every box fills. {player} scratches the {category}.",
                "{player} takes the zero on the {category}, lightly.",
                "An empty {category} for {player}. Enough said.",
                "{player} leaves the {category} at nothing. It is only a box.",
                "A zero on the {category}. {player} stays steady.",
                "{player} chooses the empty {category}. No regret needed.",
                "The {category} closes at zero for {player}.",
                "{player} takes nothing here, and nothing is taken from them.",
                "Not every roll gives. {player} scratches the {category}.",
                "{player} sets the {category} down empty.",
                "Zero, and the game goes on. {player}.",
                "{player} lets the {category} pass. Calmly.",
                "An empty box for {player}. The board is still whole.",
                "{player} accepts a zero on the {category}.",
                "Nothing on the {category}. {player} does not linger.",
                "{player} releases the {category} without a fight.",
                "The {category} ends at zero. {player} continues.",
                "{player} scratches, and the breath stays even.",
                "A quiet loss, held lightly by {player}.",
                "{player} clears the {category}. Zero, and peace.",
                "The dice asked for a zero. {player} agreed.",
                "{player} lets this one go. {category}, empty.",
                "Zero on the {category}. {player} makes room for the next turn."
            ]
        ]
    )
}
