import Foundation
import SyLibCommentary

extension CommentaryPersonality where Kind == CommentaryEventKind {
    static let steady = CommentaryPersonality(
        id: "steady",
        displayName: "Steady",
        blurb: "The understated scorekeeper — dry, factual, minimal, warm underneath.",
        prosody: CommentaryProsody(rate: 0.50, pitchMultiplier: 1.00, preUtteranceDelay: 0.10, postUtteranceDelay: 0.10),
        previewLine: "Five of a kind. Good roll.",
        lines: [
            "yatzyRolled": [
                "Yatzy for {player}. Fifty points.",
                "{player} rolls five of a kind. That's a Yatzy.",
                "There it is. Yatzy, {player}.",
                "Five matching dice. {player} takes the fifty.",
                "{player} lands the Yatzy.",
                "Clean five of a kind for {player}.",
                "That's a Yatzy on the board for {player}.",
                "{player} gets it. Fifty on the Yatzy.",
                "Five of a kind, {player}. Nicely done.",
                "Yatzy. Good roll, {player}.",
                "{player} rolls the big one. Yatzy.",
                "All five agree. Yatzy for {player}.",
                "{player} scores the Yatzy. Fifty.",
                "That'll do it. Yatzy, {player}.",
                "{player} with five of a kind.",
                "Fifty points, {player}. Yatzy.",
                "{player} closes the Yatzy box in style.",
                "Five faces, one number. {player} takes it.",
                "Solid. Yatzy for {player}.",
                "{player} rolls a Yatzy. On the board.",
                "There's the fifty. Well rolled, {player}.",
                "That is five of a kind. {player}.",
                "{player} takes the Yatzy. Fifty.",
                "Five alike. Well rolled, {player}.",
                "Yatzy on the card for {player}.",
                "{player} finds all five. Fifty points.",
                "Good one. Yatzy for {player}.",
                "{player} rolls it clean. Five of a kind.",
                "There is the Yatzy. {player}.",
                "{player} gets the fifty.",
                "Five of a kind. Nice, {player}.",
                "{player} lands all five. Yatzy.",
                "Yatzy, {player}. That is the big box.",
                "{player} takes fifty on the Yatzy.",
                "Five faces the same. Good roll, {player}.",
                "{player} rolls a Yatzy. Counted.",
                "That is the one. Yatzy for {player}.",
                "{player} fills the Yatzy. Fifty points.",
                "Five of a kind for {player}. Well done.",
                "{player} rolls it. Yatzy.",
                "Fifty for {player}. Five alike.",
                "{player} gets there. Yatzy."
            ],
            "yatzyBonusEarned": [
                "Another Yatzy for {player}. Hundred-point bonus.",
                "{player} rolls a second five of a kind. Plus one hundred.",
                "Bonus Yatzy, {player}. That's a hundred.",
                "{player} does it again. Hundred points.",
                "Second five of a kind for {player}. Bonus counts.",
                "{player} adds a hundred. Bonus Yatzy.",
                "There's another one. {player}, plus a hundred.",
                "{player} stacks a bonus Yatzy. Well rolled.",
                "Another five of a kind. Hundred to {player}.",
                "{player} earns the Yatzy bonus. A hundred.",
                "Repeat Yatzy for {player}. Points on top.",
                "{player} keeps it going. Bonus hundred.",
                "That's two now for {player}. Plus one hundred.",
                "{player} rolls the bonus. Hundred points.",
                "Another Yatzy on the board. {player}, a hundred.",
                "{player} adds to the tally. Bonus five of a kind.",
                "Second Yatzy, {player}. Counted.",
                "{player} takes the hundred-point bonus.",
                "Bonus Yatzy for {player}. Solid.",
                "{player} does it twice. A hundred more.",
                "There's the bonus, {player}. Hundred points.",
                "Two Yatzys for {player}. Hundred more.",
                "{player} rolls it again. Bonus.",
                "That is another five of a kind. {player}, plus a hundred.",
                "{player} takes a second bonus Yatzy.",
                "Another one for {player}. Hundred points.",
                "{player} rolls five alike again. Bonus counted.",
                "Bonus Yatzy. Well rolled, {player}.",
                "{player} adds another hundred to the card.",
                "Five of a kind again. {player}, bonus.",
                "That is the bonus. {player}, one hundred.",
                "{player} does it a second time. Hundred.",
                "Another Yatzy for {player}. Counted and added.",
                "{player} rolls again and gets it again. Bonus.",
                "Hundred-point bonus to {player}.",
                "{player} keeps the Yatzy box working. Bonus.",
                "Second five of a kind. {player}, plus one hundred.",
                "Bonus on the board for {player}.",
                "{player} takes another hundred. Good rolling.",
                "That is a bonus Yatzy for {player}.",
                "{player} adds a hundred. Twice now.",
                "Another five alike. {player}, bonus points."
            ],
            "winnerDeclared": [
                "{winner} wins with {score}.",
                "Final score, {winner} on top.",
                "That's the game. {winner} takes it.",
                "{winner} wins it. {score} points.",
                "Winner, {winner}. Well played.",
                "{winner} finishes first, ahead of {runnerUp}.",
                "Game over. {winner} wins by {margin}.",
                "{winner} takes the win with {score}.",
                "That's it. {winner} on top.",
                "{winner} closes it out. Winner.",
                "Final tally, {winner} first.",
                "{winner} wins. {runnerUp} second.",
                "{score} for {winner}. That's the win.",
                "{winner} takes the game.",
                "Game's done. {winner} wins by {margin}.",
                "{winner} finishes on top. {score}.",
                "Winner tonight, {winner}.",
                "{winner} holds the lead to the end.",
                "That's the match. {winner} wins.",
                "{winner} first, {runnerUp} close behind.",
                "Final: {winner}, {score}. Nicely done.",
                "{winner} finishes with {score}. That is the win.",
                "That is the game. {winner} by {margin}.",
                "{winner} wins. Good game, everyone.",
                "Final, {winner} with {score}.",
                "{winner} takes it. {runnerUp} second.",
                "Game complete. {winner} on top.",
                "{winner} holds on. Winner.",
                "That does it. {winner} wins by {margin}.",
                "{winner} first with {score}. Well played.",
                "All done. {winner} takes the game.",
                "{winner} finishes ahead of {runnerUp}.",
                "Winner is {winner}. {score} points.",
                "{winner} closes it. Nice game.",
                "That is the last box. {winner} wins.",
                "{winner} on top by {margin}.",
                "Final score {score}. {winner}.",
                "{winner} wins it. Solid card.",
                "Game's done. {winner} first.",
                "{winner} takes the win. {runnerUp} close.",
                "{winner} finishes strongest. {score}.",
                "That is a win for {winner}."
            ],
            "winnerTie": [
                "It's a tie. {winner}, both at {score}.",
                "{winner} finish level. {score} each.",
                "Tie game. {winner} share the top.",
                "{winner} tied at {score}.",
                "No single winner. {winner} split it.",
                "Even score. {winner} both first.",
                "That's a tie, {winner}.",
                "{winner} match at {score}.",
                "Dead even. {winner} share the win.",
                "{winner} tie it out. {score} apiece.",
                "Same score. {winner}, both on top.",
                "It's level. {winner} tied.",
                "{winner} finish tied. {score}.",
                "A draw. {winner} share it.",
                "Tied at {score}. {winner}.",
                "{winner} finish even.",
                "No separation. {winner} tied.",
                "{winner} both at {score}. That is a tie.",
                "Level game. {winner} share it.",
                "{winner} end up equal.",
                "That is a tie. {score} each, {winner}.",
                "{winner} come out even. Good game.",
                "Same total. {winner} tied.",
                "{winner} split the win at {score}.",
                "Tie game, {winner}.",
                "{winner} finish dead level.",
                "Even at the end. {winner}.",
                "{winner} tie at {score}. Fair enough."
            ],
            "upperBonusEarned": [
                "{player} earns the upper bonus. Thirty-five.",
                "Upper bonus for {player}. Plus thirty-five.",
                "{player} clears sixty-three. Bonus counts.",
                "That's the bonus, {player}. Thirty-five points.",
                "{player} banks the upper bonus.",
                "Sixty-three reached. {player} takes thirty-five.",
                "{player} gets the upper bonus. Good.",
                "Upper section done. {player}, plus thirty-five.",
                "{player} hits the threshold. Bonus.",
                "Thirty-five to {player}. Upper bonus.",
                "{player} secures the bonus. Nicely managed.",
                "There's the bonus. {player}, thirty-five.",
                "{player} tops sixty-three. Bonus earned.",
                "Upper bonus, {player}. On the board.",
                "{player} takes the thirty-five.",
                "Bonus counted for {player}.",
                "{player} finishes the upper section with the bonus.",
                "That threshold's cleared. {player}, plus thirty-five.",
                "{player} earns it. Upper bonus.",
                "Thirty-five points. Well played, {player}.",
                "{player} clears the threshold. Thirty-five.",
                "Upper bonus counted for {player}.",
                "{player} gets there. Bonus, thirty-five.",
                "Sixty-three for {player}. Bonus added.",
                "{player} earns the thirty-five.",
                "That is the upper bonus, {player}.",
                "{player} makes the number. Bonus.",
                "Thirty-five on the bonus line. {player}.",
                "{player} handles the upper section. Bonus.",
                "Bonus for {player}. Good management.",
                "{player} banks thirty-five.",
                "Upper section pays. {player}, thirty-five.",
                "{player} hits sixty-three. Bonus counted.",
                "That is thirty-five to {player}.",
                "{player} takes the bonus. Well played.",
                "Bonus earned. {player}, thirty-five points.",
                "{player} clears it. Upper bonus.",
                "Thirty-five for {player}. Nicely done.",
                "{player} finishes the top half with the bonus.",
                "Upper bonus lands for {player}."
            ],
            "yatzyScratched": [
                "{player} scratches the Yatzy. Zero.",
                "Zero on the Yatzy box for {player}.",
                "{player} takes a zero up top. No Yatzy.",
                "That's a scratch, {player}. Yatzy's gone.",
                "{player} zeroes the Yatzy. No bonus after this.",
                "Yatzy scratched. {player}, zero points there.",
                "{player} lets the Yatzy go. Zero.",
                "Zero in the Yatzy box. {player}'s call.",
                "{player} scratches it. No bonus insurance now.",
                "That box is closed at zero. {player}.",
                "{player} takes nothing on the Yatzy.",
                "Yatzy scratched to zero by {player}.",
                "{player} zeroes the big box. Noted.",
                "No Yatzy for {player}. Scratched.",
                "{player} writes a zero on the Yatzy.",
                "That's the Yatzy gone, {player}. Zero.",
                "{player} closes the Yatzy at zero.",
                "Zero it is. {player} scratches the Yatzy.",
                "{player} passes on the fifty. Zero.",
                "Yatzy box, zero. {player}.",
                "{player} scratches the big box. Zero.",
                "That is zero on the Yatzy, {player}.",
                "{player} gives up the fifty.",
                "Yatzy at zero. {player}'s call.",
                "{player} takes the zero. No bonus later.",
                "Scratched. {player}, zero on the Yatzy.",
                "{player} closes that box empty.",
                "No fifty for {player}. Zero.",
                "{player} zeroes it. Yatzy done.",
                "That is the Yatzy scratched, {player}.",
                "{player} writes zero in the Yatzy box.",
                "Zero there. {player} moves on.",
                "{player} sacrifices the Yatzy. Noted.",
                "The Yatzy goes empty for {player}.",
                "{player} scratches the fifty-pointer.",
                "Zero on the big one, {player}.",
                "{player} lets it go. Yatzy at zero.",
                "That box is closed. {player}, zero.",
                "{player} takes nothing on the Yatzy. Tough call.",
                "Yatzy scratched. No bonus from here, {player}."
            ],
            "bigTurn": [
                "{player} scores the {category}. {value} points.",
                "{category} for {player}. {value}.",
                "{player} takes {value} on the {category}.",
                "That's a {category}, {player}. {value}.",
                "{player} banks the {category}. {value} points.",
                "{value} for {player}. Nice {category}.",
                "{player} completes the {category}. {value}.",
                "Good turn. {player} scores {value}.",
                "{player} lands the {category} for {value}.",
                "{category}, {value}. Well played, {player}.",
                "{player} adds {value} with the {category}.",
                "That's {value} for {player}. {category}.",
                "{player} takes the {category}. {value} on the board.",
                "Solid {category} from {player}. {value}.",
                "{player} scores {value}. Good spot.",
                "{category} banked. {player}, {value}.",
                "{player} moves up with a {category}. {value}.",
                "{value} points, {player}. {category}.",
                "{player} handles the {category}. {value}.",
                "Nice one, {player}. {category} for {value}.",
                "{player} takes the {category} for {value}.",
                "{value} on the {category}. Good turn, {player}.",
                "{player} fills the {category}. {value} points.",
                "That is a strong {category}. {player}, {value}.",
                "{player} banks {value}. Well rolled.",
                "{category} for {value}. Nice work, {player}.",
                "{player} scores {value} there. Good spot.",
                "Big one. {player} takes {value}.",
                "{player} gets the {category}. {value} points.",
                "{value} added. {player}, {category}.",
                "{player} makes the {category} count. {value}.",
                "Good roll, good box. {player}, {value}.",
                "{player} takes {value} and moves up.",
                "That is {value} on the {category} for {player}.",
                "{player} lands a big {category}. {value}.",
                "{value} points. Well played, {player}.",
                "{player} converts the {category}. {value}.",
                "Nice {category}, {player}. {value} on the card.",
                "{player} scores {value}. That helps.",
                "{category} done well. {player}, {value}."
            ],
            "leadChange": [
                "{leader} takes the lead. {runnerUp} to second.",
                "New leader. {leader} in front.",
                "{leader} moves ahead of {runnerUp}.",
                "Lead change. {leader} on top.",
                "{leader} is first now.",
                "{leader} passes {runnerUp}. New leader.",
                "That puts {leader} in the lead.",
                "{leader} takes over first place.",
                "{leader} ahead. {runnerUp} close.",
                "Lead's changed. {leader} in front.",
                "{leader} moves to first.",
                "{runnerUp} drops to second. {leader} leads.",
                "{leader} is out front now.",
                "New front-runner. {leader}.",
                "{leader} takes the top spot.",
                "{leader} leads. {runnerUp} second.",
                "That's a lead change. {leader}.",
                "{leader} is first. Game's tightening.",
                "{leader} in the lead now.",
                "{leader} moves ahead. Noted.",
                "{leader} moves to the top.",
                "New leader, {leader}.",
                "{leader} ahead of {runnerUp} now.",
                "That is a lead change. {leader} first.",
                "{leader} takes over the lead.",
                "{runnerUp} slips to second. {leader} leads.",
                "{leader} in front.",
                "Lead goes to {leader}.",
                "{leader} passes {runnerUp}.",
                "{leader} is on top now.",
                "The order changes. {leader} first.",
                "{leader} takes first place.",
                "{leader} ahead. Close game.",
                "{runnerUp} second now. {leader} leads.",
                "{leader} moves up. New leader.",
                "That puts {leader} out front.",
                "{leader} leads it now.",
                "New front-runner, {leader}.",
                "{leader} at the top of the card now.",
                "{leader} first, {runnerUp} chasing."
            ],
            "turnStart": [
                "{player}'s turn.",
                "Up next, {player}.",
                "{player}, you're up.",
                "Over to {player}.",
                "{player} takes the dice.",
                "{player} rolls next.",
                "It's {player}'s turn.",
                "{player}, go ahead.",
                "Now {player}.",
                "{player} to roll.",
                "{player}'s up.",
                "Next is {player}.",
                "{player} at the tray.",
                "Your turn, {player}.",
                "{player} takes over.",
                "Here's {player}.",
                "{player}, whenever you're ready.",
                "Dice to {player}.",
                "{player} steps up.",
                "Turn goes to {player}.",
                "{player} is next.",
                "Dice go to {player}.",
                "{player}, your roll.",
                "Turn's yours, {player}.",
                "{player} up now.",
                "Over to you, {player}.",
                "{player} rolls.",
                "Next turn, {player}.",
                "{player} has the tray.",
                "Go ahead, {player}.",
                "{player} is on.",
                "That is {player}'s turn.",
                "{player}, take it away.",
                "Up to {player} now.",
                "{player} begins.",
                "Turn to {player}.",
                "{player}, roll when ready.",
                "Now it is {player}.",
                "{player} steps in.",
                "{player} takes a turn."
            ],
            "categoryScored": [
                "{player} scores {value} on the {category}.",
                "{category}, {value}. {player}.",
                "{player} puts {value} on the {category}.",
                "{value} on the {category}. {player}.",
                "{player} fills the {category}. {value}.",
                "That's {value} on the {category}, {player}.",
                "{player} logs the {category}. {value}.",
                "{category} on the board. {player}, {value}.",
                "{player} adds {value} to the {category}.",
                "{category} for {value}. {player}.",
                "{player} scores the {category} for {value}.",
                "{value} points. {player} takes the {category}.",
                "{player} takes the {category}. {value}.",
                "{category} noted for {player}. {value}.",
                "{player} moves up {value} on the {category}.",
                "{value}, {player}. {category}.",
                "{player} handles the {category}. {value}.",
                "That's the {category}. {player}, {value}.",
                "{player} writes {value} on the {category}.",
                "{value} for {player}, {category}.",
                "{player} takes {value} there.",
                "{category} filled. {player}, {value}.",
                "{value} to {player} on the {category}.",
                "{player} books {value}.",
                "That is {value}, {player}.",
                "{player} marks the {category}. {value}.",
                "{value} on the card. {player}.",
                "{player} takes {value} on the {category}. Fine.",
                "{category} closed at {value}. {player}.",
                "{player} adds {value}.",
                "{value} for the {category}. {player}.",
                "{player} scores there. {value}.",
                "That box is done. {player}, {value}.",
                "{player} puts down {value} on the {category}.",
                "{value} counted. {player}.",
                "{player} fills a box. {category}, {value}.",
                "{category}, {value} points. {player}.",
                "{player} takes it. {value}.",
                "{value} in on the {category}. {player}.",
                "{player} records {value} on the {category}."
            ],
            "categoryScratched": [
                "{player} scratches the {category}. Zero.",
                "Zero on the {category}, {player}.",
                "{player} takes nothing there.",
                "{category}, zero. {player}.",
                "{player} zeroes the {category}.",
                "That's a scratch, {player}.",
                "{player} lets the {category} go. Zero.",
                "No points on the {category}. {player}.",
                "{player} clears the {category} at zero.",
                "Zero there for {player}.",
                "{player} scratches the {category}.",
                "{category} goes empty. {player}.",
                "{player} takes a zero on the {category}.",
                "Nothing on the {category}, {player}.",
                "{player} writes off the {category}.",
                "Zero, {player}. {category}.",
                "{player} passes on the {category}. Zero.",
                "That box is zero. {player}.",
                "{player} scratches it. {category}.",
                "Empty {category} for {player}.",
                "{player} takes zero on the {category}.",
                "That is a zero, {player}.",
                "{player} empties the {category}.",
                "No points there. {player}.",
                "{player} gives up the {category}.",
                "{category} at zero for {player}.",
                "{player} takes the zero.",
                "Scratched. {player}, {category}.",
                "{player} closes the {category} empty.",
                "Zero on that one, {player}.",
                "{player} writes zero on the {category}.",
                "Nothing scored. {player}.",
                "{player} lets that box go.",
                "{category} scratched by {player}.",
                "That one goes empty, {player}.",
                "{player} takes nothing on the {category}.",
                "Zero counted. {player}.",
                "{player} scratches there. Moves on.",
                "The {category} is zero. {player}.",
                "{player} clears it at zero."
            ]
        ]
    )
}
