import Foundation

extension CommentaryPersonality {
    static let steady = CommentaryPersonality(
        id: "steady",
        displayName: "Steady",
        blurb: "The understated scorekeeper — dry, factual, minimal, warm underneath.",
        prosody: CommentaryProsody(rate: 0.50, pitchMultiplier: 1.00, preUtteranceDelay: 0.10, postUtteranceDelay: 0.10),
        previewLine: "Five of a kind. Good roll.",
        lines: [
            .yatzyRolled: [
                "Yatzy for {player}. Fifty points.",
                "{player} rolls five of a kind. That's a Yatzy.",
                "There it is. Yatzy, {player}.",
                "Five matching dice. {player} takes the fifty.",
                "{player} lands the Yatzy.",
                "Clean five of a kind for {player}.",
                "That's a Yatzy on the board for {player}.",
                "{player} gets it. Fifty on the Yatzy.",
                "Five of a kind, {player}. Nicely done.",
                "Yatzy. Good roll, {player}.",
                "{player} rolls the big one. Yatzy.",
                "All five agree. Yatzy for {player}.",
                "{player} scores the Yatzy. Fifty.",
                "That'll do it. Yatzy, {player}.",
                "{player} with five of a kind.",
                "Fifty points, {player}. Yatzy.",
                "{player} closes the Yatzy box in style.",
                "Five faces, one number. {player} takes it.",
                "Solid. Yatzy for {player}.",
                "{player} rolls a Yatzy. On the board.",
                "There's the fifty. Well rolled, {player}."
            ],
            .yahtzeeBonusEarned: [
                "Another Yatzy for {player}. Hundred-point bonus.",
                "{player} rolls a second five of a kind. Plus one hundred.",
                "Bonus Yatzy, {player}. That's a hundred.",
                "{player} does it again. Hundred points.",
                "Second five of a kind for {player}. Bonus counts.",
                "{player} adds a hundred. Bonus Yatzy.",
                "There's another one. {player}, plus a hundred.",
                "{player} stacks a bonus Yatzy. Well rolled.",
                "Another five of a kind. Hundred to {player}.",
                "{player} earns the Yatzy bonus. A hundred.",
                "Repeat Yatzy for {player}. Points on top.",
                "{player} keeps it going. Bonus hundred.",
                "That's two now for {player}. Plus one hundred.",
                "{player} rolls the bonus. Hundred points.",
                "Another Yatzy on the board. {player}, a hundred.",
                "{player} adds to the tally. Bonus five of a kind.",
                "Second Yatzy, {player}. Counted.",
                "{player} takes the hundred-point bonus.",
                "Bonus Yatzy for {player}. Solid.",
                "{player} does it twice. A hundred more.",
                "There's the bonus, {player}. Hundred points."
            ],
            .winnerDeclared: [
                "{winner} wins with {score}.",
                "Final score, {winner} on top.",
                "That's the game. {winner} takes it.",
                "{winner} wins it. {score} points.",
                "Winner, {winner}. Well played.",
                "{winner} finishes first, ahead of {runnerUp}.",
                "Game over. {winner} wins by {margin}.",
                "{winner} takes the win with {score}.",
                "That's it. {winner} on top.",
                "{winner} closes it out. Winner.",
                "Final tally, {winner} first.",
                "{winner} wins. {runnerUp} second.",
                "{score} for {winner}. That's the win.",
                "{winner} takes the game.",
                "Game's done. {winner} wins by {margin}.",
                "{winner} finishes on top. {score}.",
                "Winner tonight, {winner}.",
                "{winner} holds the lead to the end.",
                "That's the match. {winner} wins.",
                "{winner} first, {runnerUp} close behind.",
                "Final: {winner}, {score}. Nicely done."
            ],
            .winnerTie: [
                "It's a tie. {winner}, both at {score}.",
                "{winner} finish level. {score} each.",
                "Tie game. {winner} share the top.",
                "{winner} tied at {score}.",
                "No single winner. {winner} split it.",
                "Even score. {winner} both first.",
                "That's a tie, {winner}.",
                "{winner} match at {score}.",
                "Dead even. {winner} share the win.",
                "{winner} tie it out. {score} apiece.",
                "Same score. {winner}, both on top.",
                "It's level. {winner} tied.",
                "{winner} finish tied. {score}.",
                "A draw. {winner} share it."
            ],
            .upperBonusEarned: [
                "{player} earns the upper bonus. Thirty-five.",
                "Upper bonus for {player}. Plus thirty-five.",
                "{player} clears sixty-three. Bonus counts.",
                "That's the bonus, {player}. Thirty-five points.",
                "{player} banks the upper bonus.",
                "Sixty-three reached. {player} takes thirty-five.",
                "{player} gets the upper bonus. Good.",
                "Upper section done. {player}, plus thirty-five.",
                "{player} hits the threshold. Bonus.",
                "Thirty-five to {player}. Upper bonus.",
                "{player} secures the bonus. Nicely managed.",
                "There's the bonus. {player}, thirty-five.",
                "{player} tops sixty-three. Bonus earned.",
                "Upper bonus, {player}. On the board.",
                "{player} takes the thirty-five.",
                "Bonus counted for {player}.",
                "{player} finishes the upper section with the bonus.",
                "That threshold's cleared. {player}, plus thirty-five.",
                "{player} earns it. Upper bonus.",
                "Thirty-five points. Well played, {player}."
            ],
            .yatzyScratched: [
                "{player} scratches the Yatzy. Zero.",
                "Zero on the Yatzy box for {player}.",
                "{player} takes a zero up top. No Yatzy.",
                "That's a scratch, {player}. Yatzy's gone.",
                "{player} zeroes the Yatzy. No bonus after this.",
                "Yatzy scratched. {player}, zero points there.",
                "{player} lets the Yatzy go. Zero.",
                "Zero in the Yatzy box. {player}'s call.",
                "{player} scratches it. No bonus insurance now.",
                "That box is closed at zero. {player}.",
                "{player} takes nothing on the Yatzy.",
                "Yatzy scratched to zero by {player}.",
                "{player} zeroes the big box. Noted.",
                "No Yatzy for {player}. Scratched.",
                "{player} writes a zero on the Yatzy.",
                "That's the Yatzy gone, {player}. Zero.",
                "{player} closes the Yatzy at zero.",
                "Zero it is. {player} scratches the Yatzy.",
                "{player} passes on the fifty. Zero.",
                "Yatzy box, zero. {player}."
            ],
            .bigTurn: [
                "{player} scores the {category}. {value} points.",
                "{category} for {player}. {value}.",
                "{player} takes {value} on the {category}.",
                "That's a {category}, {player}. {value}.",
                "{player} banks the {category}. {value} points.",
                "{value} for {player}. Nice {category}.",
                "{player} completes the {category}. {value}.",
                "Good turn. {player} scores {value}.",
                "{player} lands the {category} for {value}.",
                "{category}, {value}. Well played, {player}.",
                "{player} adds {value} with the {category}.",
                "That's {value} for {player}. {category}.",
                "{player} takes the {category}. {value} on the board.",
                "Solid {category} from {player}. {value}.",
                "{player} scores {value}. Good spot.",
                "{category} banked. {player}, {value}.",
                "{player} moves up with a {category}. {value}.",
                "{value} points, {player}. {category}.",
                "{player} handles the {category}. {value}.",
                "Nice one, {player}. {category} for {value}."
            ],
            .leadChange: [
                "{leader} takes the lead. {runnerUp} to second.",
                "New leader. {leader} in front.",
                "{leader} moves ahead of {runnerUp}.",
                "Lead change. {leader} on top.",
                "{leader} is first now.",
                "{leader} passes {runnerUp}. New leader.",
                "That puts {leader} in the lead.",
                "{leader} takes over first place.",
                "{leader} ahead. {runnerUp} close.",
                "Lead's changed. {leader} in front.",
                "{leader} moves to first.",
                "{runnerUp} drops to second. {leader} leads.",
                "{leader} is out front now.",
                "New front-runner. {leader}.",
                "{leader} takes the top spot.",
                "{leader} leads. {runnerUp} second.",
                "That's a lead change. {leader}.",
                "{leader} is first. Game's tightening.",
                "{leader} in the lead now.",
                "{leader} moves ahead. Noted."
            ],
            .turnStart: [
                "{player}'s turn.",
                "Up next, {player}.",
                "{player}, you're up.",
                "Over to {player}.",
                "{player} takes the dice.",
                "{player} rolls next.",
                "It's {player}'s turn.",
                "{player}, go ahead.",
                "Now {player}.",
                "{player} to roll.",
                "{player}'s up.",
                "Next is {player}.",
                "{player} at the tray.",
                "Your turn, {player}.",
                "{player} takes over.",
                "Here's {player}.",
                "{player}, whenever you're ready.",
                "Dice to {player}.",
                "{player} steps up.",
                "Turn goes to {player}."
            ],
            .categoryScored: [
                "{player} scores {value} on the {category}.",
                "{category}, {value}. {player}.",
                "{player} takes {value}.",
                "{value} for {player}.",
                "{player} fills the {category}. {value}.",
                "That's {value}, {player}.",
                "{player} logs the {category}. {value}.",
                "{value} on the board. {player}.",
                "{player} adds {value}.",
                "{category} for {value}. {player}.",
                "{player} scores there. {value}.",
                "{value} points, {player}.",
                "{player} takes the {category}. {value}.",
                "Noted, {value} for {player}.",
                "{player} moves up {value}.",
                "{value}, {player}. {category}.",
                "{player} handles the {category}. {value}.",
                "That's {value} added. {player}.",
                "{player} scores {value}.",
                "{value} for {player}, {category}."
            ],
            .categoryScratched: [
                "{player} scratches the {category}. Zero.",
                "Zero on the {category}, {player}.",
                "{player} takes nothing there.",
                "{category}, zero. {player}.",
                "{player} zeroes the {category}.",
                "That's a scratch, {player}.",
                "{player} lets the {category} go. Zero.",
                "No points on the {category}. {player}.",
                "{player} clears the {category} at zero.",
                "Zero there for {player}.",
                "{player} scratches the {category}.",
                "{category} goes empty. {player}.",
                "{player} takes a zero on the {category}.",
                "Nothing on the {category}, {player}.",
                "{player} writes off the {category}.",
                "Zero, {player}. {category}.",
                "{player} passes on the {category}. Zero.",
                "That box is zero. {player}.",
                "{player} scratches it. {category}.",
                "Empty {category} for {player}."
            ]
        ]
    )
}
