import Foundation

extension CommentaryPersonality {
    static let zen = CommentaryPersonality(
        id: "zen",
        displayName: "Zen",
        blurb: "The mindful narrator — calm, present-tense, gently wry serenity.",
        prosody: CommentaryProsody(rate: 0.42, pitchMultiplier: 0.96, preUtteranceDelay: 0.35, postUtteranceDelay: 0.30),
        previewLine: "Five dice, one mind. Everything arrives in its own time.",
        lines: [
            .yatzyRolled: [
                "Five dice, one mind. {player} finds the Yatzy.",
                "Everything settles into place for {player}. A Yatzy.",
                "{player} rolls, and the dice agree. Yatzy.",
                "Stillness, then five of a kind. Well done, {player}.",
                "The path opened for {player}. A quiet fifty.",
                "All five aligned. {player} receives a Yatzy.",
                "{player} lets go, and the dice arrive together.",
                "A moment of harmony. Five faces, one for {player}.",
                "No forcing, only flow. {player} lands the Yatzy.",
                "{player} breathes, and the dice fall as one.",
                "Five as one. {player} meets the Yatzy.",
                "The dice found their center for {player}.",
                "What is meant to arrive, arrives. {player}, a Yatzy.",
                "{player} rolls with an open hand. Five of a kind.",
                "Presence rewarded. {player} takes the fifty.",
                "Calm hands, five faces. A Yatzy for {player}.",
                "{player} and the dice, briefly, in perfect agreement.",
                "The moment ripened. {player} gathers a Yatzy.",
                "Five dice at rest, all the same. Peace, and a Yatzy, for {player}.",
                "{player} did nothing extra, and everything worked. Yatzy.",
                "A small miracle on the table. {player}, five of a kind."
            ],
            .yatzyBonusEarned: [
                "Again, the dice align for {player}. A hundred more, received quietly.",
                "The flow continues. {player} finds another five of a kind.",
                "What began, continues. {player} takes the bonus.",
                "{player} stays present, and the dice return. A hundred points.",
                "No grasping, only more. {player} earns the bonus Yatzy.",
                "The stream keeps flowing for {player}. Another hundred.",
                "{player} rolls again, and again it is five as one.",
                "Abundance, without effort. {player} gathers a hundred.",
                "The moment repeats itself gently. {player}, a bonus Yatzy.",
                "{player} remains calm, and the dice remain kind. Plus one hundred.",
                "Once more the faces agree. Well done, {player}.",
                "{player} does not chase it, and it comes anyway.",
                "The wave carries {player} a little further. A hundred more.",
                "Stillness, then five of a kind. Twice now, {player}.",
                "{player} accepts the bonus as it is given.",
                "What is flowing does not stop for {player}. Another hundred.",
                "Balance holds. {player} rolls a second Yatzy.",
                "{player} breathes, and a hundred points arrive.",
                "The dice keep their promise to {player}. Bonus Yatzy.",
                "Again, effortless. {player} takes the hundred.",
                "{player} and fortune, still walking together."
            ],
            .winnerDeclared: [
                "The game rests. {winner} arrives at the top, with {score}.",
                "All turns complete. {winner} holds the highest score.",
                "{winner} finishes gently ahead. {score} points.",
                "The path led here. {winner}, this game is yours.",
                "Nothing left to roll. {winner} settles into first.",
                "{winner} and {runnerUp} both played well. Tonight, {winner} leads.",
                "The dice are still. {winner} carries the game, by {margin}.",
                "Completion. {winner} takes the win, softly.",
                "{winner} reaches the summit without hurry. {score}.",
                "The final rest. {winner} on top.",
                "A good game, well played by all. {winner} first.",
                "{winner} closes the circle with {score}.",
                "Effort and ease, in balance. {winner} wins.",
                "The game exhales. {winner}, the winner.",
                "{winner} arrives where the game was going. First place.",
                "All is scored. {winner} holds the lead, {score}.",
                "{runnerUp} pressed close. {winner} kept the calm, and the win.",
                "{winner} finishes present and steady. The game is theirs.",
                "Peace on the table. {winner} takes it.",
                "The last die settles. {winner} wins, by {margin}.",
                "Well played, everyone. {winner}, the quiet victor."
            ],
            .winnerTie: [
                "Two paths, one summit. {winner} arrive together, at {score}.",
                "A tie. {winner} share the game, and the peace.",
                "No one ahead, no one behind. {winner}, level at {score}.",
                "Balance itself. {winner} finish as equals.",
                "The game holds no single winner. {winner} share it.",
                "{winner} meet at the same place. {score} each.",
                "Perfect symmetry. {winner} tied.",
                "Neither above the other. {winner} rest as one.",
                "A shared summit for {winner}. {score}.",
                "The dice divided nothing. {winner} tie.",
                "Equal effort, equal end. {winner}, together at {score}.",
                "{winner} arrive side by side. A gentle tie.",
                "No division tonight. {winner} share the win.",
                "Stillness, and a tie. {winner}, both first."
            ],
            .upperBonusEarned: [
                "Patience rewarded. {player} earns the upper bonus.",
                "{player} tended the small numbers, and the bonus arrived.",
                "Steady work brings its gift. {player}, thirty-five points.",
                "{player} reaches sixty-three, and the bonus follows.",
                "Nothing rushed. {player} gathers the upper bonus.",
                "The quiet effort pays. {player} takes the thirty-five.",
                "{player} kept to the path, and the path gave back.",
                "Small stones build the wall. {player} earns the bonus.",
                "{player} arrives at sixty-three, gently. Bonus received.",
                "The upper section, complete for {player}. Thirty-five.",
                "{player} planted early and harvests now.",
                "Attention to the little things. {player}, the bonus is yours.",
                "{player} let the numbers add themselves. Bonus earned.",
                "Diligence, made visible. {player} takes the thirty-five.",
                "{player} crosses the threshold with ease. Bonus.",
                "The upper bonus settles on {player}, well deserved.",
                "{player} kept the balance up top, and it held. Bonus.",
                "Slow and sure, {player} claims the thirty-five.",
                "{player} finishes the upper work in peace.",
                "Sixty-three, and beyond. {player} receives the bonus."
            ],
            .yatzyScratched: [
                "{player} releases the Yatzy, and takes nothing. Sometimes we let go.",
                "A zero on the Yatzy. {player} chooses to release the fifty.",
                "{player} scratches the box. What is empty stays empty. It is enough.",
                "Not every door opens. {player} sets the Yatzy aside.",
                "{player} accepts a zero. Attachment released.",
                "The Yatzy passes by. {player} does not grasp it.",
                "{player} lets the fifty go without regret. Or with some. That is honest.",
                "A scratch. {player} makes peace with the empty box.",
                "{player} closes the Yatzy quietly. No bonus will come. So it is.",
                "Sometimes the roll asks for a sacrifice. {player} gives the Yatzy.",
                "{player} takes the zero, and breathes. The game continues.",
                "What could have been fifty becomes zero. {player} accepts it.",
                "{player} scratches the box. Loss, held lightly.",
                "The Yatzy is released by {player}. Onward, gently.",
                "{player} lets it be zero. There is freedom in that too.",
                "No Yatzy this game for {player}. The board narrows. Notice it.",
                "{player} surrenders the fifty. A small letting-go.",
                "The box empties by choice. {player} moves on.",
                "{player} scratches the Yatzy, and the mind stays calm.",
                "Zero, chosen freely by {player}. Even loss can be clean."
            ],
            .bigTurn: [
                "{player} completes the {category}. {value} points, arriving in order.",
                "The pattern reveals itself. {player}, a {category} for {value}.",
                "{player} lets the dice fall into place. {category}, {value}.",
                "Form emerges. {player} scores {value} on the {category}.",
                "{player} finds the {category}. {value}, without strain.",
                "A shape completed. {player} takes {value}.",
                "{player} gathers the {category}, worth {value}. Well seen.",
                "The dice arrange themselves for {player}. {category}, {value}.",
                "{player} scores the {category}. {value} points, quietly earned.",
                "Everything in sequence. {player}, {value} on the {category}.",
                "{player} sees the pattern and takes it. {value}.",
                "A {category} for {player}. {value}, received.",
                "{player} completes the shape. {value} points.",
                "The right pieces, in the right places. {player}, {value}.",
                "{player} claims the {category}, worth {value}. Steady work.",
                "Balance on the board. {player} scores {value}.",
                "{player} finishes the {category} with a calm hand. {value}.",
                "Order from the roll. {player}, {value} points.",
                "{player} takes the {category}. {value}, no fuss.",
                "The dice cooperate. {player} banks {value} on the {category}."
            ],
            .leadChange: [
                "The lead shifts, softly. {leader} moves ahead of {runnerUp}.",
                "{leader} rises to the front. The game breathes and changes.",
                "Nothing stays fixed. {leader} now leads.",
                "{leader} steps ahead of {runnerUp}. The current turns.",
                "The tide comes in for {leader}. First place, for now.",
                "{leader} takes the lead, and holds it lightly.",
                "Positions flow. {leader} ahead, {runnerUp} close.",
                "{leader} moves forward. All places are temporary.",
                "The front belongs to {leader} in this moment.",
                "{leader} passes {runnerUp}. The river keeps moving.",
                "A gentle shift. {leader} now leads.",
                "{leader} rises without pushing. First place.",
                "The lead changes hands, calmly. {leader} in front.",
                "{leader} ahead now. {runnerUp} need not worry. It flows both ways.",
                "{leader} takes the top, for as long as it lasts.",
                "The game turns toward {leader}. First place.",
                "{leader} steps into the lead, quietly.",
                "Ahead and behind trade places. {leader} leads.",
                "{leader} moves to first. Nothing is settled yet.",
                "The lead rests with {leader} now. Watch it change again."
            ],
            .turnStart: [
                "{player}'s turn. Breathe, then roll.",
                "The dice come to {player}.",
                "It is {player}'s moment now.",
                "{player} takes the dice, gently.",
                "Whenever you're ready, {player}.",
                "The turn passes to {player}.",
                "{player}, the table is yours.",
                "Now {player}. No hurry.",
                "{player} arrives at their turn.",
                "The dice rest, waiting for {player}.",
                "{player}, take your time.",
                "A new turn opens for {player}.",
                "{player} steps in, calm.",
                "The moment is {player}'s.",
                "{player}, roll when the mind is still.",
                "Over to {player}, softly.",
                "{player} receives the dice.",
                "Presence, please, {player}. Your turn.",
                "{player}'s turn begins.",
                "The dice belong to {player} now."
            ],
            .categoryScored: [
                "{player} takes {value} on the {category}. Onward.",
                "The {category}, filled. {player}, {value}.",
                "{player} places {value} on the {category}, calmly.",
                "A quiet {value} on the {category}. {player}.",
                "{player} scores the {category}. {value} points.",
                "{value} added to the {category}, without fuss. {player}.",
                "{player} completes the {category}. {value}.",
                "The {category} grows the board by {value}. {player}.",
                "{player} sets the {category} at {value}, gently.",
                "{category}, {value}. {player} moves on.",
                "{player} takes what the roll offered. {category}, {value}.",
                "A small step on the {category}. {player}, {value}.",
                "{player} fills the {category}. {value}.",
                "{value} on the {category}, received. {player}.",
                "{player} takes the {category}. {value}. Enough.",
                "The {category} settles at {value}. {player}.",
                "{player} adds {value} on the {category} and lets it be.",
                "{value} for {player} on the {category}. Enough for now.",
                "{player} places the {category}. {value}.",
                "A steady {value} on the {category}. {player}."
            ],
            .categoryScratched: [
                "{player} releases the {category}. Zero. It is fine.",
                "A zero on the {category}. {player} lets it pass.",
                "{player} sets the {category} aside, empty.",
                "Not this one. {player} scratches the {category}.",
                "{player} takes nothing, and takes it well.",
                "The {category} goes to zero. {player} moves on.",
                "{player} lets the {category} be empty. No harm.",
                "A quiet zero for {player} on the {category}.",
                "{player} releases the {category}. Onward.",
                "Nothing here. {player} accepts the {category} as zero.",
                "{player} scratches gently. {category}, zero.",
                "Some rolls ask for nothing. {player} scratches the {category}.",
                "{player} lets the {category} go without a fight.",
                "A zero, chosen. {player} clears the {category}.",
                "{player} makes peace with an empty {category}.",
                "The {category} rests at zero. {player} continues.",
                "{player} gives up the {category}, calmly.",
                "Not every box fills. {player} scratches the {category}.",
                "{player} takes the zero on the {category}, lightly.",
                "An empty {category} for {player}. Enough said."
            ]
        ]
    )
}
