import Foundation
import SyLibCommentary

extension CommentaryPersonality where Kind == CommentaryEventKind {
    static let sports = CommentaryPersonality(
        id: "sports",
        displayName: "Sports",
        blurb: "The broadcast booth — energetic, hyperbolic, sports clichés for dice.",
        prosody: CommentaryProsody(rate: 0.54, pitchMultiplier: 1.08, preUtteranceDelay: 0.05, postUtteranceDelay: 0.05),
        previewLine: "Five of a kind, folks! The crowd is absolutely losing it right now!",
        lines: [
            "yatzyRolled": [
                "Yatzy! {player} brings the house down!",
                "Five of a kind! {player} rolls the perfect one, folks!",
                "Are you kidding me? {player} nails the Yatzy!",
                "That is a Yatzy for {player}, and the crowd goes wild!",
                "Textbook! Five dice, one face, all {player}!",
                "{player} calls their shot and delivers a Yatzy!",
                "Oh, {player} dialed that one up! Yatzy on the board!",
                "Five for five! {player} with the roll of the night!",
                "Send it! {player} lands the Yatzy clean!",
                "History right there, folks. {player} rolls a Yatzy!",
                "{player} steps up and drops fifty on us. Yatzy!",
                "Unbelievable scenes! Yatzy for {player}!",
                "That is what a Yatzy looks like, courtesy of {player}!",
                "Boom! {player} clears the whole board with five of a kind!",
                "{player} with the dagger. Yatzy, ballgame energy!",
                "Five matching dice for {player} and this table is electric!",
                "{player} came to play. That is a Yatzy!",
                "Perfect roll, perfect timing, all {player}. Yatzy!",
                "Right on the money! {player} rolls the fifty-pointer!",
                "And there it is! {player} joins the Yatzy club!",
                "{player} just made this look easy. Yatzy!",
                "Are you serious? {player} with five of a kind!",
                "{player} goes and does it! Yatzy on the board!",
                "Get the replay ready! {player} just rolled a Yatzy!",
                "That is a fifty-point statement from {player}!",
                "{player} shows up when it counts! Yatzy!",
                "Nothing but matching faces! {player} takes the Yatzy!",
                "Oh my word! {player} rolls five of the same!",
                "{player} answers the bell! That is a Yatzy!",
                "The tray erupts! {player} with five of a kind!",
                "{player} puts fifty on the board just like that!",
                "Call it! {player} rolled the Yatzy!",
                "Clean as it gets! Yatzy for {player}!",
                "{player} steps into the moment and delivers! Yatzy!",
                "Five identical dice! {player} owns this table!",
                "That is a career roll from {player}! Yatzy!",
                "{player} with a Yatzy and this place is shaking!",
                "Down goes the board! {player} rolls five of a kind!",
                "You will see that one again tonight, folks. {player}, Yatzy!",
                "{player} lights it up! Fifty points, five dice!",
                "Are we watching the same game? {player} rolls a Yatzy!",
                "{player} finds the perfect roll! Yatzy!"
            ],
            "yatzyBonusEarned": [
                "Another one?! {player} with the bonus Yatzy, plus a hundred!",
                "{player} is on fire! Back-to-back five of a kind!",
                "Stop it! {player} rolls ANOTHER Yatzy! Hundred more!",
                "The bonus is live and {player} is cashing it! A hundred points!",
                "{player} does it again, folks! Bonus Yatzy!",
                "Lightning strikes twice for {player}! Plus one hundred!",
                "Who does that? {player} does that! Another Yatzy!",
                "{player} just added a hundred like it was nothing!",
                "Encore! {player} rolls the bonus five of a kind!",
                "That's a second Yatzy for {player} and the booth is losing it!",
                "{player} keeps rolling and the points keep coming! Hundred more!",
                "Absolute heater from {player}! Bonus Yatzy on the board!",
                "{player} is in the zone! Another hundred, another Yatzy!",
                "Ridiculous! {player} stacks a bonus Yatzy!",
                "The hot hand stays hot! {player}, plus one hundred!",
                "{player} with the repeat performance! Bonus points!",
                "Again?! {player} cannot be stopped! Another Yatzy!",
                "Cash it in, {player}! A hundred-point bonus Yatzy!",
                "{player} rolls a second five of a kind! Unreal!",
                "The bonus banner is up! {player} adds one hundred!",
                "{player} just turned this into a highlight reel!",
                "Twice now! {player} adds another hundred!",
                "{player} is not done! A second five of a kind!",
                "Somebody check the dice! {player} rolls another Yatzy!",
                "The bonus board lights up again for {player}!",
                "{player} doubles down and gets it! Plus a hundred!",
                "Another Yatzy, folks! {player} is rewriting the night!",
                "{player} with the follow-up! Bonus five of a kind!",
                "You cannot script this! {player} rolls a bonus Yatzy!",
                "{player} strikes again! A hundred more on the board!",
                "That is two! {player} with the bonus and the swagger!",
                "The run continues! {player} banks another hundred!",
                "{player} keeps the heater going! Bonus Yatzy!",
                "Back for more! {player} lands a second five of a kind!",
                "{player} makes it look routine! Another hundred!",
                "The booth is out of words! {player}, bonus Yatzy!",
                "{player} piles it on! One hundred more points!",
                "Second verse, same as the first! Yatzy for {player}!",
                "{player} finds it again! Bonus points on the board!",
                "Look out! {player} rolls another Yatzy!",
                "{player} tacks on a hundred like it is nothing!",
                "Two Yatzys in one game for {player}! Special stuff!"
            ],
            "winnerDeclared": [
                "That's the ballgame! {winner} takes it with {score}!",
                "Final score, {winner} on top! What a performance!",
                "{winner} wins it, folks! {score} points and a trophy!",
                "Ballgame! {winner} holds off {runnerUp} for the title!",
                "{winner} closes it out! Champion, right here!",
                "It's over, and {winner} stands alone! {score} to win!",
                "{winner} brings it home by {margin}! Sensational!",
                "Your winner tonight, {winner}, with {score}!",
                "{winner} seals the deal! {runnerUp} left in second!",
                "Final horn! {winner} is your champion!",
                "{winner} finishes strong and takes the crown!",
                "What a run by {winner}! Winner, {score} points!",
                "{winner} did it! Edging {runnerUp} for the win!",
                "Game, set, match, {winner}! {score} on the board!",
                "{winner} climbs to the top! Champion by {margin}!",
                "And {winner} takes it! The comeback complete!",
                "{winner} wins the night! Textbook finish!",
                "Final tally, {winner} on top with {score}!",
                "{winner} outlasts the field! Your winner!",
                "Champagne for {winner}! The title is theirs!",
                "{winner} closes the show! {score} and the win!",
                "That is your final! {winner} takes it with {score}!",
                "{winner} finishes it off! {runnerUp} runs out of road!",
                "The buzzer sounds! {winner} wins by {margin}!",
                "{winner} is your champion tonight! {score} points!",
                "All over! {winner} holds on for the win!",
                "{winner} takes the title! What a night at the tray!",
                "Put it in the books! {winner} with {score}!",
                "{winner} answers every challenge! Winner!",
                "It is done! {winner} beats {runnerUp} to the finish!",
                "{winner} closes the door! Champion by {margin}!",
                "Final scoreboard, {winner} on top!",
                "{winner} came to win and did exactly that! {score}!",
                "That is the game! {winner} raises the trophy!",
                "{winner} finishes the job! {runnerUp} second!",
                "The champion is {winner}, and it is well earned!",
                "{winner} runs out the clock! {score} to take it!",
                "Hand it over! The win belongs to {winner}!",
                "{winner} takes it going away! {margin} points clear!",
                "What a performance! {winner} wins the night!",
                "{winner} stands tallest! Final score {score}!",
                "That is a wrap! {winner} is your winner!"
            ],
            "winnerTie": [
                "We've got a tie! {winner}, deadlocked at {score}!",
                "Photo finish, folks! {winner} share the top!",
                "No separation! {winner} tied at {score}!",
                "Dead heat! {winner} both on top!",
                "Unbelievable, a tie! {winner} split the crown!",
                "Nobody blinks! {winner} finish level at {score}!",
                "It's all square! {winner} tied for the win!",
                "What a finish! {winner} can't be separated!",
                "Even Steven! {winner} share it at {score}!",
                "A tie for the ages! {winner} both champions!",
                "Deadlocked! {winner} tied to the point!",
                "They match to the number! {winner}, {score} apiece!",
                "No winner alone tonight! {winner} share it!",
                "A draw! {winner} both walk away on top!",
                "Nothing between them! {winner} tied at {score}!",
                "Down to the wire and level! {winner} share it!",
                "A tie at the top! {winner}, {score} each!",
                "They finish shoulder to shoulder! {winner}!",
                "Not a point in it! {winner} tied!",
                "Both champions tonight! {winner} at {score}!",
                "The scoreboard says tie! {winner} splitting the honors!",
                "Neither backs down! {winner} finish level!",
                "What a finish, folks! {winner} tied at {score}!",
                "Too close to call! {winner} share the top!",
                "Level pegging! {winner} both on {score}!",
                "They matched each other all night! {winner}, tied!",
                "No separation at the buzzer! {winner}!",
                "It ends even! {winner} share the win!"
            ],
            "upperBonusEarned": [
                "{player} locks in the upper bonus! Thirty-five more!",
                "There's the bonus! {player} cracks sixty-three!",
                "{player} does the upper work and cashes in! Plus thirty-five!",
                "Bonus secured! {player} banks the thirty-five!",
                "{player} grinds it out and gets the upper bonus!",
                "Smart play by {player}! The bonus is theirs!",
                "{player} hits the number! Thirty-five-point bonus!",
                "Upper section, handled! {player} takes the bonus!",
                "{player} punches the ticket! Bonus points on the board!",
                "That's the bonus for {player}! The fundamentals pay off!",
                "{player} clears sixty-three and pockets thirty-five!",
                "Bonus in the bank for {player}!",
                "{player} plays it right and gets rewarded! Upper bonus!",
                "There it is, the thirty-five! Nice work, {player}!",
                "{player} secures the upper bonus like a pro!",
                "Ballgame fundamentals from {player}! Bonus earned!",
                "{player} tops the threshold! Thirty-five, please!",
                "The upper bonus belongs to {player}!",
                "{player} closes the upper section in style! Bonus!",
                "Thirty-five points, courtesy of {player}'s discipline!",
                "{player} does the little things right! Upper bonus!",
                "Bonus points! {player} clears the sixty-three mark!",
                "{player} takes care of business up top! Thirty-five!",
                "The upper section pays out for {player}!",
                "{player} banks the bonus! Fundamentals, folks!",
                "That is thirty-five for {player}! Big pickup!",
                "{player} finishes the upper drive! Bonus!",
                "Textbook work from {player}! Upper bonus secured!",
                "{player} gets to sixty-three and cashes in!",
                "The bonus is on the board for {player}!",
                "{player} does the dirty work and gets paid! Thirty-five!",
                "Upper bonus! {player} makes the numbers work!",
                "{player} takes the thirty-five and the momentum!",
                "That is how you build a score! {player}, bonus!",
                "{player} converts! Upper bonus, thirty-five points!",
                "Right through the threshold! {player} takes the bonus!",
                "{player} banks it! Thirty-five more on the board!",
                "Bonus time for {player}! The upper section delivers!",
                "{player} closes out the top half with a bonus!",
                "Thirty-five for {player}! Every point counts!"
            ],
            "yatzyScratched": [
                "Ohh, {player} scratches the Yatzy! No bonus insurance now!",
                "Big swing! {player} zeroes out the Yatzy box!",
                "That's a scratch on the Yatzy for {player}! Gutsy or grim, you decide!",
                "{player} takes a zero on the Yatzy! The bonus door slams shut!",
                "Yikes! {player} lets the Yatzy go for nothing!",
                "{player} scratches the fifty-pointer! No safety net!",
                "There goes the Yatzy box, zeroed by {player}!",
                "{player} eats a zero up top! No more bonus chances!",
                "Tough break, folks! {player} scratches the Yatzy!",
                "{player} writes a zero where fifty could've been!",
                "The Yatzy box is dead for {player}! Scratched!",
                "{player} sacrifices the Yatzy! High-stakes stuff!",
                "Zero on the Yatzy! {player} closes that door!",
                "{player} scratches it! No bonus Yatzy in this player's future!",
                "Painful! {player} takes nothing on the Yatzy!",
                "{player} zeroes the big box! The gamble is on!",
                "That's a scratch, {player}! The Yatzy's off the table!",
                "{player} lets the fifty slip to zero!",
                "No Yatzy for {player} tonight! Scratched clean!",
                "{player} poisons the box! Zero on the Yatzy!",
                "{player} takes a zero on the Yatzy! What a swing!",
                "The Yatzy box goes empty for {player}! Costly!",
                "{player} gives up the fifty! No coming back from that!",
                "Ouch! {player} scratches the biggest box on the card!",
                "{player} takes the zero and the risk with it!",
                "That is a scratch on the Yatzy! {player} gambles on the rest of the card!",
                "No fifty for {player} tonight! Zero on the Yatzy!",
                "{player} shuts the bonus door themselves! Scratched!",
                "Big decision, big consequences! {player} zeroes the Yatzy!",
                "{player} takes nothing where fifty lived! Tough!",
                "The Yatzy is gone for {player}! Zeroed out!",
                "{player} scratches! That box is done for the night!",
                "Hard to watch! {player} zeroes the Yatzy!",
                "{player} plays the odds and loses the fifty!",
                "That is a zero on the Yatzy box, {player}!",
                "{player} lets the big one slip away! Scratched!",
                "Down goes the Yatzy! {player} takes a zero!",
                "{player} spends the Yatzy on nothing! Brutal!",
                "Scratched clean! No Yatzy bonus for {player}!",
                "{player} closes the fifty-point door! Zero!"
            ],
            "bigTurn": [
                "{player} drops a {category} for {value}! Big points!",
                "That's a {category}! {player} banks {value}!",
                "{player} with the {category}, worth {value}!",
                "Huge turn! {player} scores {value} on the {category}!",
                "{player} cashes the {category}! {value} on the board!",
                "Order up! {player} completes the {category} for {value}!",
                "{player} nails the {category}! That's {value}, folks!",
                "Big number from {player}! {category}, {value} points!",
                "{player} lines up the {category}! {value}!",
                "There's the {category} for {player}! {value} points!",
                "{player} delivers the {category}! {value} banked!",
                "Textbook {category} by {player}! {value}!",
                "{player} strikes gold! {category} for {value}!",
                "{player} loads up the {category}! {value} points!",
                "Momentum swing! {player} scores {value} on the {category}!",
                "{player} with a statement {category}! {value}!",
                "That'll move the needle! {player}, {category}, {value}!",
                "{player} takes the {category} and runs! {value}!",
                "Big-time roll! {player} banks {value} with the {category}!",
                "{player} finishes the {category} in style! {value}!",
                "{player} goes big on the {category}! {value} points!",
                "There is the {category}! {player} takes {value}!",
                "{player} makes it count! {value} on the {category}!",
                "Huge! {player} converts the {category} for {value}!",
                "{player} lands the {category} and banks {value}!",
                "That {category} is worth {value} to {player}!",
                "{player} swings the momentum! {category}, {value}!",
                "Points on the board! {player}, {value} on the {category}!",
                "{player} finds the {category}! {value} big ones!",
                "Clutch roll! {player} scores {value} on the {category}!",
                "{player} converts the {category} for {value}!",
                "The {category} belongs to {player}! {value} points!",
                "{player} pounces on the {category}! {value}!",
                "Big-time {category} from {player}! {value} on the board!",
                "{player} takes {value} and shifts this game!",
                "That is a difference-maker! {player}, {category}, {value}!",
                "{player} rolls into the {category}! {value} points!",
                "Score it up! {player} banks {value} on the {category}!",
                "{player} delivers when it matters! {value} on the {category}!",
                "Watch the total climb! {player}, {category} for {value}!"
            ],
            "leadChange": [
                "New leader! {leader} surges past {runnerUp}!",
                "And {leader} takes the lead! What a swing!",
                "{leader} moves to the front! {runnerUp} bumped to second!",
                "Lead change! {leader} is your new front-runner!",
                "{leader} storms into first! {runnerUp} gives chase!",
                "There's the swing! {leader} on top now!",
                "{leader} grabs the lead from {runnerUp}!",
                "The order flips! {leader} leads!",
                "{leader} vaults ahead! {runnerUp} in the rearview!",
                "New number one! {leader} takes command!",
                "{leader} snatches the lead! Game on!",
                "{runnerUp} yields the top spot to {leader}!",
                "{leader} is out front! The race is heating up!",
                "And just like that, {leader} leads!",
                "{leader} overtakes {runnerUp}! Momentum shift!",
                "The lead is {leader}'s now! Big move!",
                "{leader} pulls to the front! Watch out, {runnerUp}!",
                "Changing of the guard! {leader} on top!",
                "{leader} takes over first place!",
                "{runnerUp} led, but now it's all {leader}!",
                "{leader} charges to the front! {runnerUp} slides back!",
                "Big move! {leader} takes over the lead!",
                "{leader} is your new leader! What a run!",
                "The top spot changes hands! {leader} in front!",
                "{leader} pushes past {runnerUp}! New number one!",
                "There goes the lead! {leader} takes it!",
                "{leader} climbs into first! The pressure is on {runnerUp}!",
                "Momentum swing! {leader} out in front!",
                "{leader} makes the move! {runnerUp} answers next!",
                "New leader on the board! {leader}!",
                "{leader} surges! {runnerUp} down to second!",
                "The lead flips! {leader} on top now!",
                "{leader} takes command of this game!",
                "Look at {leader} go! First place!",
                "{runnerUp} loses the top spot to {leader}!",
                "{leader} muscles into the lead! Great turn!",
                "That does it! {leader} is your front-runner!",
                "{leader} passes {runnerUp} and keeps going!",
                "The scoreboard flips! {leader} leads!",
                "{leader} makes the leap to first!"
            ],
            "turnStart": [
                "{player} steps up to the tray!",
                "Here comes {player}!",
                "{player} is on the clock!",
                "Up next, {player}!",
                "{player} takes the dice!",
                "It's {player}'s turn, folks!",
                "{player} ready to roll!",
                "All eyes on {player}!",
                "{player} at the table!",
                "Here's {player}!",
                "{player} to the dice!",
                "{player}'s up!",
                "Let's see what {player} has!",
                "{player} takes their shot!",
                "The dice are {player}'s!",
                "{player} on deck and rolling!",
                "Over to {player}!",
                "{player} enters the arena!",
                "{player} steps in!",
                "Time for {player}!",
                "{player} is called up!",
                "Now rolling, {player}!",
                "{player} takes center stage!",
                "The dice go to {player}!",
                "{player}, let us see it!",
                "Turn belongs to {player}!",
                "{player} is up next!",
                "Here we go, {player}!",
                "{player} at the tray!",
                "Big turn ahead for {player}!",
                "{player} gets the call!",
                "Roll them, {player}!",
                "{player} takes the stage!",
                "The table turns to {player}!",
                "{player} is in!",
                "Your turn, {player}!",
                "{player} steps to the line!",
                "Watch {player} work!",
                "{player} takes over!",
                "It is on {player} now!"
            ],
            "categoryScored": [
                "{player} takes {value} on the {category}.",
                "{category} for {player}, {value} points.",
                "{player} banks {value} on the {category}!",
                "On the board! {player} with {value} on the {category}!",
                "{player} scores the {category}. {value}.",
                "That's {value} for {player} on the {category}!",
                "{player} plays the {category}. {value}.",
                "{value} points on the {category} for {player}!",
                "{player} logs {value} on the {category}.",
                "Solid {category}, {value} for {player}!",
                "{player} adds {value} with the {category}!",
                "{category}, {value}. {player} keeps moving.",
                "{player} puts up {value} on the {category}!",
                "{value} in the books, {category} for {player}!",
                "{player} takes care of the {category}. {value}.",
                "{category} points for {player}, {value}!",
                "{player} chalks up {value} on the {category}!",
                "That's the {category}, {value}, {player}.",
                "{player} moves the total with a {category}. {value}!",
                "{value} more on the {category} for {player}!",
                "{player} adds {value} on the {category}!",
                "The {category} goes for {value}! {player}!",
                "{player} gets on the board with {value}!",
                "{value} on the {category}. {player} keeps it rolling.",
                "{player} takes the {category} for {value}!",
                "Points for {player}! {category}, {value}!",
                "{player} works the {category}. {value} scored.",
                "There is {value} on the {category} for {player}!",
                "{player} takes what is there. {category}, {value}.",
                "{value} points added by {player} on the {category}!",
                "{player} handles the {category} for {value}!",
                "Onto the card! {player}, {value} on the {category}!",
                "{player} counts up {value} on the {category}!",
                "The {category} is done. {player}, {value}.",
                "{player} banks another {value}!",
                "Good management! {player}, {value} on the {category}.",
                "{value} on the {category} and {player} moves along!",
                "{player} fills the {category}. {value} on the board!",
                "That is {value} more for {player}!",
                "{category} scored! {value} to {player}!"
            ],
            "categoryScratched": [
                "{player} scratches the {category}. Zero there.",
                "Nothing on the {category} for {player}.",
                "{player} takes a zero on the {category}.",
                "That's a scratch, {player}. {category}, zero.",
                "{player} lets the {category} go.",
                "Zero on the {category} for {player}.",
                "{player} eats a goose egg on the {category}.",
                "No points on the {category}, {player}.",
                "{player} writes off the {category}.",
                "A scratch on the {category} for {player}.",
                "{player} zeroes the {category}.",
                "{category}, zero. Tough one, {player}.",
                "{player} sacrifices the {category}.",
                "Nothing doing on the {category} for {player}.",
                "{player} clears the {category} at zero.",
                "Zero there, {player}. On to the next.",
                "{player} bites the bullet on the {category}.",
                "Scratch on the {category}, {player}.",
                "{player} takes nothing on the {category}.",
                "{category} goes empty for {player}.",
                "{player} comes up empty on the {category}.",
                "The {category} goes for nothing, {player}.",
                "{player} takes the zero and moves along.",
                "No luck on the {category} for {player}.",
                "{player} punts the {category}. Zero.",
                "That one is a wash. {category}, zero for {player}.",
                "{player} scratches. The {category} is off the card.",
                "Empty box on the {category} for {player}.",
                "{player} cuts the losses on the {category}.",
                "Zero it is, {player}. The {category} closes.",
                "{player} takes a blank on the {category}.",
                "Nothing there, folks. {player} scratches the {category}.",
                "{player} gives up the {category}. No points.",
                "The dice would not cooperate. Zero for {player}.",
                "{player} moves on from the {category}. Zero.",
                "Tough turn. {player} scratches the {category}.",
                "{player} settles for nothing on the {category}.",
                "The {category} comes off the board at zero, {player}.",
                "{player} eats a zero there.",
                "No damage on the {category} for {player}."
            ]
        ]
    )
}
